### ISSUE TITLE
[Regression] Driven Audio Sources Now Glitch Constantly.

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#1198] opened 2020-10-25 15:52 UTC
As of the latest (audio) update, driving sounds via the Logix audio drive node with a timer (duration into a %) just results in a crackly/staticky mess. Here's before the update:
https://cdn.discordapp.com/attachments/439422229986410499/769951433818374204/2020-10-25_01-59-59.mp4

But now it sounds like this:
https://cdn.discordapp.com/attachments/731903736028332083/769949381062557696/BrokenCat.ogg

**Comment by Frooxius** [comment] 2020-10-25 15:58
This is not a regression, this wasn't supported in the first place. Audio playback requires very precise sub-frame timing to work correctly, which you can't achieve with LogiX since it's bound to the frame update rate, so you end up forcing the audio to constantly jump around by tiny increments.

However the drive playback node now has a new feature to actually properly handle this, using the MaximumPositionError. I recommend using this and plugging some small tolerance value, which will prevent the node from seeking the audio source if the position is close enough.

**Comment by Enverex** [comment] 2020-10-25 16:34
That value appears to have no effect what-so-ever, regardless of setting - https://cdn.discordapp.com/attachments/731903736028332083/769960947250364476/2020-10-25_16-28-36.mp4

The issue could infact be this though instead - https://github.com/Frooxius/NeosPublic/issues/1199

**Comment by Enverex** [comment] 2020-10-25 16:36
Removing the VolumeMeter does infact fix it, so it's that issue.

https://cdn.discordapp.com/attachments/731903736028332083/769962564192174110/2020-10-25_16-35-49.mp4

**Comment by Frooxius** [comment] 2020-10-25 16:38
Ah yeah, if the value has no effect, then the driving is not the culprit. I'll close this issue then and work on a hotfix for the other one. Thanks!

**Closed by Frooxius** 2020-10-25 16:38 UTC
Labels: Not a Bug
