### ISSUE TITLE
Avatar scaling occurs when Trying to scale an object

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#540] opened 2020-05-14 08:09 UTC
This typically will happen in the cases another grabbable, or your trying to scale an object that is in your hand. A good example of this occuring is with Aegis's crossbow if your grabbing the reload mechanism, while gripping the other(I.e a slider). The result is scale to a maxium amount of some kind. If you need help reproducing I can get video.

**Comment by ProbablePrime** [comment] 2020-05-14 19:30
I've read this 3 times and I'm still unsure what you're referring to. But to me it seems like a configuration issue on the gadget itself. Could you try re-stating the issue?

**Comment by TehTurk** [comment] 2020-05-14 19:32
Hmm, I had it occur in the last Community Showcase stream toward the end of April if you need footage. Essentially, there are occasions where gripping an object.on a tool/gun/toy that's equipped will have you size exponentially to some bigger size. This normally happens when there's a slider object on a tool and your trying to adjust some dial, level or such.

**Comment by ProbablePrime** [comment] 2020-05-14 19:35
Your avatar or the object?

**Comment by TehTurk** [comment] 2020-05-14 19:36
My avatar, I should have specified.

**Comment by Frooxius** [comment] 2020-05-18 09:49
Should be fixed in 2020.5.18.573 thanks! Let me know if the issue is still occurring.

**Closed by Frooxius** 2020-05-18 09:49 UTC
Labels: bug
