### ISSUE TITLE
[UIX] "Join" button persists on friend list

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#411] opened 2020-03-02 09:47 UTC
The "join" button can frequently be seen on sessions where joining isn't possible, e.g. private sessions.

This button clears itself properly after a cursor passes over it.

**Comment by Frooxius** [comment] 2020-03-11 21:13
Fixed in 2020.3.11.1193 thanks!

**Comment by shiftyscales** [comment] 2020-03-14 23:24
This is still a recurring issue on the latest build- 2020.3.14.776.

**Comment by Frooxius** [comment] 2020-03-15 14:06
This seems to be a different cause. Do you have a way of replicating this reliably? I cannot reproduce the issue with my original testing scenario (I simply open the friends list, start another user account on my laptop and toggle between public and private worlds. The "Join" button goes away as expected).

**Comment by shiftyscales** [comment] 2020-03-15 15:25
I believe this one happens when the friend list is closed during the state/session privacy change.

**Comment by Frooxius** [comment] 2020-03-20 00:31
Closing this because it was fixed for the remainder of cases.

**Closed by Frooxius** 2020-03-20 00:31 UTC
Labels: UI/UX, bug
