### ISSUE TITLE
Tool lasers pass through the first object they hit

### ISSUE THREAD

**Issue by DeliriousJax** [Frooxius/NeosPublic#528] opened 2020-05-11 06:04 UTC
When using some tools such as the grabber setter tool or logix tool, the laser goes through the first item/collider it hits and goes to the second collider behind that.

Recreate:
Equip a logix or grabber setter tool. Attempt to place said tool on your tool shelf using trigger while another collider is below or past your tool shelf from the trigger's perspective. Then try to place the tool on your tool shelf with nothing beyond your hand from the laser's perspective.

**Comment by mralext20** [comment] 2020-05-11 06:05
extension or dupe of #527

**Closed** 2020-05-11 06:14 UTC
Labels: duplicate
