### ISSUE TITLE
Prefer Audio Only Incompatible With Livestreams

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1528] opened 2020-12-24 01:25 UTC
## Describe
After loading in a livestream (example taken from YouTube), the video will play normally until the option PreferAudioOnly is selected. Upon doing so, the video stream will display a blank image with no sound until the option is disabled.

This issue could only be performed when using the libVLC playback engine, as Unity Native was unable to display livestreams during testing.

In the event that this is a third party issue that cannot be resolved, a possible solution may be to disable the PreferAudioOnly checkbox when playing a livestream. This will avoid confusing users and resulting in suspected errors.

## Bug information
 - How often does it happen: Always
 - Neos Version: Tested in 2020.12.24.35, existed in previous
 - Neos Platform: Windows
 - Regression: No

**Comment by Frooxius** [comment] 2020-12-24 01:27
Do you have log? Usually it prints out available streams, so those might be helpful to diagnose what's going on.

**Comment by LeDrascol** [comment] 2020-12-24 01:52
A log has been posted at the url below.

> https://pastebin.com/raw/wJ93sE3g

**Comment by Frooxius** [comment] 2020-12-24 02:02
Is this a single attempt to load the stream or multiple in that log?

**Comment by LeDrascol** [comment] 2020-12-24 02:24
The option was toggled on and off multiple times, including changing the playback engine and requested resolution at some points. If necessary, the issue can be reproduced in a more isolated environment to create simpler logs.

**Comment by Frooxius** [comment] 2020-12-28 16:39
Thanks for the info. It looks like Neos is picking the right stream, but libVLC is unable to play it. I've tried it with latest standalone VLC app as well and it's not able to play the stream either, so the issue is external to Neos. It might be youtube-dlc reporting invalid streams.

Unfortunately there's not much we can do when playing from services like YouTube and such, the success rate for the stream won't be 100 %, I'd recommend using a custom audio streaming service for that instead, since you can have more control over it and get better reliability.

I'm going to close this one as it's not a bug on Neos side.

Unfortunately it is not possible to disable the checkbox. For one, there's not really a mechanism for that in general, as it's a representation of the data model and it's in part on side of the user to provide proper settings. But for this specifically it's also chicken and egg problem - you can't tell that the URL is a stream until it's actually processed and parsed and even then it's not always clear if it represents a media with fixed size or livestream until it's fully loaded. And since fails to fully load I can't tell that it's a stream.

**Closed by Frooxius** 2020-12-28 16:39 UTC
Labels: Bug
