### ISSUE TITLE
Avatars with changeable heights or proportions cause Physical Locomotion collision issues

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#823] opened 2020-07-29 01:30 UTC
GearBell has created an avatar which can shrink and grow in size, It's the slime one you may have seen. When it shrinks or grows it does not affect the overall User scale.

When this avatar shrinks its size its physical locomotion collider is not updated to reflect the new size. The result is a shrunken avatar with a regular sized locomotion collider.

Presented on the left is the issue and on the right is the desired outcome of the shrinking of the avatar:
![text4545-6](https://user-images.githubusercontent.com/8791132/88745932-13c36880-d100-11ea-8a41-e5297ed348a7.png)

Currently, GearBell has to inject a custom PhysicalLocomotion module into the user's locomotion modules to allow for this. While this works it unfourtunately won't work on certain maps in which the using of custom locomotion modules is blocked via the permission system. For an example setup that blocks locomotion modules see: https://www.youtube.com/watch?v=sn1iF8zs5P4 or my permission system tutorials.

Could the avatar height changing(presumably their bounding box) be linked to their physical locomotion collider's height in some way automatically?

**Comment by shiftyscales** [comment] 2020-07-29 01:37
This can be considered as a duplicate of #585, like #753 and #763. In order to achieve this, Frooxius wishes to first implement bepuphysicsv2 as a pre-requisite, this subject can be re-evaluated then.

Changing the height of the character controller dynamically is expensive, particularly on the current version of bepu, and it can also potentially be prone to potential bugs.

Right now, all users are treated as 1.9m tall by the default character controller regardless of their actual height too.

**Closed by shiftyscales** 2020-07-29 01:37 UTC
Labels: Avatar System, enhancement, locomotion

**Comment by ProbablePrime** [comment] 2020-07-29 01:39
Thanks!
