### ISSUE TITLE
Rift S tutorial is classic rift controller

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#817] opened 2020-07-28 01:56 UTC
Discovered by Linkodemayo

**Comment by Frooxius** [comment] 2020-07-28 02:52
What do you mean by this? Which tutorial are you talking about? The picture on the dash? The model in the MTC? The overlay model?

Are they running through native Oculus runtime or through SteamVR?

**Comment by Hayden-da-Serg** [comment] 2020-07-28 03:07
Pretty sure he means the tutorial models on the hands when "Hide All Tutorials" is unchecked, and I can confirm that this is the case. I'm using the Quest/Rift S controllers but the CV1 models still render. I'm using a Quest via Virtual Desktop running through SteamVR.

**Comment by Frooxius** [comment] 2020-07-28 07:59
I see. I checked those and looks like the Rift S versions of those were never actually made. Well set some up, thank you!

**Comment by Earthmark** [comment] 2020-07-28 08:26
Apologies, I got very lost in VR and finally found my way back. Thanks for the update Hayden and thanks for finding the issue Froox! Also thanks Shifty for the poke.

I'll leave it open for you to close Froox.

**Comment by Frooxius** [comment] 2020-07-28 08:28
No worries. Rue is making the tutorial versions of the controllers now, I'll close it once they're out. Thanks!

**Comment by RueShejn** [comment] 2020-07-28 11:36
Controllers are done!
Froox should be adding them to a nightly build to test soon

**Comment by Frooxius** [comment] 2020-07-29 12:19
Both Quest and RiftS should now show the right controller in 2020.7.29.725 now, thanks!

**Closed by Frooxius** 2020-07-29 12:19 UTC
Labels: tweak
