### ISSUE TITLE
AssetFrameAudio captures other AssetFrames

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#1291] opened 2020-11-06 21:35 UTC
There is a couple of problems with the AssetFrame component when trying to do a couple of things.

1. When removing audio orbs from an assetframe, sometimes, no matter how far away you put it, it goes right back into the frame. I can't seem to find a rhyme or reason to this. It might be more desirable to have the asset drop into AssetFrame only when interacting with it's collider.
1. Asset frame with an audio orb in it will become attached to another asset frame, resulting in asset frame inception. I'm not sure how to avoid this as it's probably a bubbling hierarchy operation, but if it could only accept the audio orb itself and not it's parent, that might be desirable. Or possibly some sort of white/black listing?

Here's a video of this happening:
https://youtu.be/0SoHJMYTr4A

**Comment by shiftyscales** [comment] 2020-11-06 21:40
The first point is a duplicate of #695. The underlying issue seems to be tied to if text is present. If an object has text on it, e.g. like the audio clip does, the asset frame grabs it from a really long range.

**Comment by Frooxius** [comment] 2020-11-08 10:12
Both should be fixed in 2020.11.8.605! It was indeed related to text, but the underlying issue was even deeper. This should fix a lot of other strange behaviors too. Thanks!

**Closed by Frooxius** 2020-11-08 10:12 UTC
