### ISSUE TITLE
Strip Empty Blendshapes does not respect N/A blendshapes

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1329] opened 2020-11-13 19:36 UTC
As the title suggests, the Strip Empty Blendshapes button on SkinnedMeshRenderer does not respect any blendshapes titled N/A, these would be blendshapes that would be added in Neos after the model is imported or after a mesh is transferred to another SkinnedMeshRenderer

To replicate, navigate to a SkinnedMeshRenderer that has Blendshapes, click Add Blendshape until ones with the name N/A are displayed, then click Strip Empty Blendshapes, notice that it will say "Done! Stripped: 0 blendshapes"

**Comment by shiftyscales** [comment] 2020-11-13 19:56
Duplicate of #390, relevant Frooxius quote:
> That's not what the button does. "Strip empty blendshapes" removes them from the mesh. The ones you see in the inspector are just the configuration for renderer. The Add button is more or an artifact, it needs proper UI for editing them.

**Comment by Frooxius** [comment] 2020-11-13 20:38
Yeah that's correct, this button works on the mesh data, not on the actual blendshape weights.

**Closed by Frooxius** 2020-11-13 20:38 UTC
