### ISSUE TITLE
Ref Arrows have repeating, not clamped texture.

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1681] opened 2021-01-27 08:01 UTC
## Is your tweak request related to a problem? Please describe.
The texture on a ref arrow is repeating which makes its wide border show up on the thin edge.

## Describe what would you like tweaked
Change the default texture to clamp instead of repeat.

## Describe alternatives you've considered
Keeping it like this or changing it in every session manually.

**Comment by 3x1t-5tyl3** [comment] 2021-01-27 08:05
Duplicate of #1093

**Comment by Frooxius** [comment] 2021-01-27 08:06
Yeah this is duplicate of https://github.com/Frooxius/NeosPublic/issues/1093

**Closed by Frooxius** 2021-01-27 08:06 UTC
Labels: Tweak

**Comment by Psychpsyo** [comment] 2021-01-27 08:09
Sorry for often not finding these before I open new ones.
