### ISSUE TITLE
Weird userspace instability at the latest creator jam

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#773] opened 2020-07-13 18:32 UTC
Hello,

At the latest creator Jam I had a lot of instability around the area of userspace interactions. There were quite a few symptoms:
- Keyboard refused to open. (Another user reported this here: https://discordapp.com/channels/402159838827905024/439421735474036738/732216088007540739)
- Radial Context Menu refused to open or opened and was white and several magnitudes of scale smaller than it should be
- Friends list on the dash would not scroll it just stopped rendering after one page
- A persistent collider of some sort was present in front of my hands causing purple lasers
- Tabs of the dash were unresponsive causing problems going between them

Before this was happening I was within the creator jam 59 world which focused on twitch interactions. I was editing the channel which a TwitchInterface component was set to before this started happening. In particular I was using a value copy operation on the TwitchInterface component. 

This seems like it was a bad idea as the TwitchInterface appeared to re-connect each time a single character was changed. I think this could have caused the issues described above as the Twitch connection might have been re-establishing many connections every time the channel changed by a character.

I changed the setup I describe above to write the channel name to the interface once editing was finished and **restarted Neos**. I wasn't able to re-produce the issue after making this change but I did want to get the log file here so that it can be checked for any underlying issues that might be fixable.

I took a look at error logs and have attached one that has a lot of content within it. I see some things that appear to match up with some of my above list. I also see some stuff suggesting that its hitting Twitch Rate Limits too.

The logfile is 31MB Which is... quite a lot larger than the usual log file. So I hope its helpful. GH doesn't want to take a file larger than 10MB so here it is: https://i.probableprime.co.uk/200713-Rsucj92WMQnOICnjgs14.log

**Comment by shiftyscales** [comment] 2020-07-13 19:03
The log is quite verbose, and it looks like each of the above issues were caught as various exceptions. There's quite a lot to go through here, but it looks like a bulk of the log was filled with errors getting the global positions for various UIX bits after they had already broken in various places from when a DevToolTip tried to open a gizmo by selecting something.

**Comment by Frooxius** [comment] 2020-07-13 22:52
Hmm this sounds like the background processing might've been overwhelmed with too many jobs and the jobs responsible for updating your lasers and the UI were simply getting stuck in the queue.

This is a bit harder to access/fix in general, as it's more of a pathological behavior, rather than any kind of bug. I'd need some way to replicate this to address it, with one time occurrence I'm not sure there will be much to do. It might not even be fully solvable then, if whatever was happening in the world caused this, as it's more akin to OS getting slow and unresponsive when there are too many apps draining the system resources.

I see some bugs in the log, I'll try to fixup those, but none of them look like they'd be responsible for this.

**Comment by ProbablePrime** [comment] 2020-07-13 23:24
Ok thank you, I'll take a look and see if I notice it again, If I do i'll grab more logs and i'll see if there's some underlying cause I can replicate.

Thankyou.

**Comment by ProbablePrime** [comment] 2020-07-13 23:47
Other users are reporting similar issues whilst having the twitch chat Dialog out. I will ask them to send logs here to see if it has the same Background jobs issue.

**Comment by Frooxius** [comment] 2020-07-14 00:06
I see. It might be something on it overloading the background jobs. Is that just the regular chat dialog or just in this particular case?

For something like this I'd need to replicate the issue and narrow it down, the background jobs are not generally going to show up in the log.

You could try to open the Debug dialog though and open the Background Jobs page and watch what happens.

**Comment by Frooxius** [comment] 2020-07-24 07:47
I've added a thing in 2020.7.24.446 that helps diagnose background jobs. When you experience this again, mash the F9 key on  your keyboard for about 10-20 seconds, then send the logs (after you exit Neos). It will log the state of background processing into them.

**Comment by Frooxius** [comment] 2020-07-27 00:19
I've added more diagnostics in 2020.7.27.3, if you experience this problem again, please send new logs with the latest build!

**Comment by Vigilabo** [comment] 2020-07-30 22:08
This is similar what happened for me. When creating a link using the envelope button my UI stopped responding/updating. It affects all UI and stops them from responding/updating.
Here is a log: [DESKTOP-7Q9M270 - 2020.7.29.748 - 2020-07-30 17_55_11.log](https://github.com/Frooxius/NeosPublic/files/5004002/DESKTOP-7Q9M270.-.2020.7.29.748.-.2020-07-30.17_55_11.log)

**Comment by TheRealBobotron** [comment] 2020-08-11 15:22
This is still an issue, and it happens consistently while im streaming

This issue is replicable by going into a blank world and duplicating a twitch chat a bunch 

Its driving me insane..

**Comment by Frooxius** [comment] 2020-08-11 16:40
@TheRealBobotron Sorry you're still having issues, but thanks so much for that replication step, that's what I've been missing until now! I managed to reproduce it on my end, which will make it much easier to fix, rather than relying on reports from others.

**Comment by Frooxius** [comment] 2020-08-11 21:49
Ok, I've spent several hours on this, but it's unfortunately a lot more complicated. The main problem is that the Twitch library we're using has really poorly written multithreading and Task usage, using lots of synchronous locks and sleeping, which ends up starving the threadpool, so the UIX updates sometimes end up waiting for up to 10-15 seconds in the queue. 

I've reworked some central parts of the library to use proper async patterns, which seems to have helped somewhat, although it's a bit hard to tell. I'll push it out in the next build and see if the improves on your end in regular usage.

Part of the problem is that Unity's Mono implementation doesn't seem to follow the behaviors of some Threading.Task related classes that .NET Framework does, which further complicates things, as continuations of the UIX calculations get scheduled asynchronously, even though they should run immediately and as a result end up subject to the long wait.

Does your Twitch chat reinitialize itself often or change the URL during normal use? Or do you have multiple instances of it in the world? I've also added some more info to the log which could help diagnose those issues.

**Comment by Ruikio** [comment] 2020-08-11 22:11
I normally only have one Twitch chat interface in the world at  a time. Sometimes I'll pull out a Twitch chat facet aswell so there may be two. This issue happens regardless if there is one or two. I've been smashing F9 for the passed couple days where I get locked out of my UI/Dash. 

Twitch chat does not reinitialize itself. It's just, normal and living. Unlike my UI that is.

**Comment by Frooxius** [comment] 2020-08-11 22:15
Hmm it might be reconnecting itself in the background perhaps. I've added things so that will now be logged. I'll push out the update soon and we'll see if it helps or gather some more info. The important thing is I have now a way to replicate it, so that will make it much faster to narrow down a solution.

**Comment by Frooxius** [comment] 2020-08-11 22:59
@TheRealBobotron @Ruikio I've pushed a new build 2020.8.11.1368 which has the mitigations and extra logging. Can you run on that one and check if the issue still occurs? If it does, please send me logs, they should now have some more diagnostic information.

**Comment by TheRealBobotron** [comment] 2020-08-13 01:26
Thank you froox! so far no issues, ill update this if i experience it again but as for now thank you!! first time in 3 months ive been able to play neos without UI glitch! <3

**Comment by Frooxius** [comment] 2020-08-13 04:38
Ah that's good news so far, thank you! :D I was a bit worried that spending a half a day digging around it would be for nothing x3 But let me know if there are still issues.

**Comment by H3BO3** [comment] 2020-09-28 17:17
Closing this issue since no more replies have been made. Please reopen it if there are related issues.

**Closed by H3BO3** 2020-09-28 17:17 UTC
Labels: Bug, needs more information
