### ISSUE TITLE
Host user Undo Actions sometimes propagates to all users when interfacing with Color fields

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1266] opened 2020-11-03 14:18 UTC
I think this has been an issue for as long as I've been in Neos, but never bothered to report it.
I don't entirely know what causes this to happen, but sometimes when the host user is interacting with a color field, their undo steps propagate to all users currently present.

**Comment by Frooxius** [comment] 2020-11-03 17:46
- What exactly do you mean by their undo steps propagating to all users present? 
- What do the other users observe on their end?
- What does the Undo Manager look like when this happens?

**Comment by chemicalcrux** [comment] 2020-12-27 00:10
I experienced this today. A driven Color ValueField was causing my undo history to be spammed with "set field" events; this was also affecting another person in the instance, who was the host. The undo was also propagated when manually editing the field. I wasn't able to gather any other information, unfortunately.

**Comment by Frooxius** [comment] 2020-12-27 03:17
I think you actually found the reason. Changing a driven value will force it to be reset back to the driven value and just in general interact oddly.

I'll make some changes to prevent that from happening. If anyone could confirm that it's indeed happening with values that are driven (might depend on how the value is being changed though) that could help.

**Comment by shiftyscales** [comment] 2020-12-27 04:38
@Frooxius Cyro and I confirmed this is the case. Specifically though, this had occurred when using:
- ValueField<color>
- T > Hue Logix nodes driving the value field
- Open the color wheel
- While the color wheel is open, all users in the session will have an undo entry added for it

Other methods such as using a value copy/value driver didn't seem to replicate this behavior.

**Comment by Frooxius** [comment] 2020-12-31 00:07
Should be fixed in 2020.12.30.1285, thank you!

**Closed by Frooxius** 2020-12-31 00:07 UTC
Labels: Bug
