### ISSUE TITLE
Reparenting the roles and assets slots

### ISSUE THREAD

**Issue by art0007i** [Frooxius/NeosPublic#717] opened 2020-06-25 05:37 UTC
It is possible to reparent the roles and assets slots by dragging a slot into their parent field
![bug](https://user-images.githubusercontent.com/19620451/85660516-0147b080-b6b6-11ea-9655-d636b406ffac.gif)
Attempting to delete the new parent will freeze the game
A similar thing can be done to the world root but that does not seem to affect anything

**Comment by shiftyscales** [comment] 2020-06-25 23:39
I believe there are protections in place to prevent modification/removal/deletion of the roles/assets slots. Unfortunately on replicating this issue, I've noted there doesn't appear to be any exceptions thrown in the log. But the issue is perfectly replicable.

Thanks for the report.

**Comment by Frooxius** [comment] 2020-07-02 02:42
Fixed in 2020.7.2.150, thanks!

**Closed by Frooxius** 2020-07-02 02:42 UTC
Labels: bug
