### ISSUE TITLE
Slot Child Events Bug: event is too fast?

### ISSUE THREAD

**Issue by ukilop** [Frooxius/NeosPublic#1335] opened 2020-11-15 03:58 UTC
This bug was observed with slot child events but I have a feeling it applies to other events as well.
in both vr and desktop log states same error `
Exception:
System.Exception: Modification of the element is currently blocked, cannot modify`

Reproduction:
make empty slot,
give it 3 children, in my example named A, B, and C
write some logic so that on slot child event(of slot B) slot added it tries to reparent the added slot to C
if you manually reparent A to B (through inspector)
user is deleted and A is parented under B
if this reparent is done with logix (or desktop) the user is not deleted but the error is still logged and A is still under B (even though inspector inspecting A says it's parent is C)

log provided from desktop attempt
[2020.11.13.1356 - 2020-11-14 21_38_07.log](https://github.com/Frooxius/NeosPublic/files/5541824/2020.11.13.1356.-.2020-11-14.21_38_07.log)

Took a while to figure out that this was the problem I was running into when trying to debug some logix, 
in the end an updates delay fixes everything

**Comment by TehTurk** [comment] 2020-11-16 17:01
This makes sense, the events are supposed to be used with in mind of not expecting things to be in a normal operation standard for most slots. As it fires right after the slot is moved/added. It's ill-advised to use too much with SlotEvents as it was warned when this node was originally made to be careful with it, because before the original usage was to track children account and use that as such. The parenting operation happens after the event. I'm going to close this issue as this is within expected behavior, but if anyone wants to reopen feel free.

**Closed by TehTurk** 2020-11-16 17:01 UTC
