### ISSUE TITLE
[Bug] Avatar creator consistently deletes users 

### ISSUE THREAD

**Issue by LewisSnow** [Frooxius/NeosPublic#535] opened 2020-05-13 02:58 UTC
Constantly I've noticed that the avatar creator deletes users on pressing create, I have no idea what the conditions should be for this to happen, as of right now it seems to be consistently random. It even happens with only one person in the session, no one else.

**Comment by shiftyscales** [comment] 2020-05-13 04:29
I believe this could possibly be a duplicate of this issue: https://github.com/Frooxius/NeosPublic/issues/385

Would you be able to confirm this, @LewisSnow?

**Comment by LewisSnow** [comment] 2020-05-13 04:49
yes, that issue #385  is the reason why it deletes user

**Comment by shiftyscales** [comment] 2020-05-13 04:52
Okay, marking this one as a duplicate and closing it.

**Closed by shiftyscales** 2020-05-13 04:52 UTC
Labels: bug, duplicate
