### ISSUE TITLE
Bug Report: Grabbable Parenter component broken - wont unparent afterwards

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#738] opened 2020-07-04 00:23 UTC
Grabbable Parenter is working in that when the item enters the collider with the component it does work in parenting but then it wont unparent even after grabbing the item and moving it far away.

**Comment by ProbablePrime** [comment] 2020-07-04 00:30
I'm not sure this is a bug. Grabbable Parenter doesn't appear to have any configuration it may be a class which other components inherit.

**Comment by GearBell** [comment] 2020-07-04 00:39
then Request: please add a Unparent On Grab checkbox?

**Comment by ProbablePrime** [comment] 2020-07-04 00:40
The thing is im not sure you're meant to be using this component. I've tried it and tried to make a tutorial for it but it seems to just grab stuff when its remotely close to the object. That isn't really ideal.

What's the scenario you're trying to use it for?

**Comment by shiftyscales** [comment] 2020-07-04 00:42
There is a property on grabbables "ReparentOnRelease". Unchecking that will ensure the grabbable won't be reparented under the slot it was grabbed from after the grabbable parenter picked it up.

**Comment by ProbablePrime** [comment] 2020-07-04 00:42
This component sucks grabbables in and parents them to itself though. I don't think it respects that option.

**Comment by shiftyscales** [comment] 2020-07-04 00:43
I believe that component opperates based on a collider though, doesn't it? I'll need to investigate.

**Comment by ProbablePrime** [comment] 2020-07-04 00:44
It doesn't I've tried it multiple times. At this point we should wait for Froox to answer with the technical information about this component.

**Comment by H3BO3** [comment] 2020-07-04 00:58
I would like to use this component if this change is made

**Comment by shiftyscales** [comment] 2020-07-04 01:08
It isn't bugged- that is how it was designed. It does require a collider somewhere in the hierarchy as that is how it detects the grabbables.

The issue is in that the component also uses the collider of all child objects too- so the effective range of the component just swells and swells, compounded with it that it doesn't release the objects unless the 'reparent on release' of the grabbables are unchecked.

**Comment by ProbablePrime** [comment] 2020-07-04 01:21
That makes sense, It was my colliders growing causing my observation. Thank you!

**Comment by Frooxius** [comment] 2020-07-04 04:07
If you want to prevent things from being reparented under it, attach GrabbableReparentBlock (under Transform/Interaction) on it. It's not responsibility of this component to handle this.

One thing I'm going to add to GrabbableParenter is ability to override where the objects get parented, that way you can split up the detection hierarchy, from the location where it gets parented.

**Comment by H3BO3** [comment] 2020-07-04 04:09
I'd love to have a collider zone that automatically parents grabbables released inside it to itself, but unparent when you grab and remove them from the zone. This would also create some functionality @GearBell was wanting.

**Comment by Frooxius** [comment] 2020-07-04 04:11
Like I mentioned in my message, add GrabbableReparentBlock to the root where they get parented. That will prevent them from being re-parented when released away.

**Comment by H3BO3** [comment] 2020-07-04 04:15
Is it possible similar behavior is what's causing the assetframe bug  https://github.com/Frooxius/NeosPublic/issues/695 ?

**Comment by Frooxius** [comment] 2020-07-04 04:16
No, that one blocks grabbable reparenting implicitly.

**Comment by H3BO3** [comment] 2020-07-04 04:19
Hopefully that other bug can be fixed soon, it's kind of annoying having to do testing with broken frames

**Comment by Frooxius** [comment] 2020-07-04 12:47
Ok 2020.7.4.755 now has "ParentUnder" which lets you separate where the parented objects go. This will avoid their colliders form being used for checking the parenting. 

If you want to prevent the reparenting when releasing anywhere, you still need to use the GrabbableReparentBlock though.

**Closed by Frooxius** 2020-07-04 12:47 UTC
Labels: Components, not a bug, tweak
