### ISSUE TITLE
Camera mode for capturing 360 Stereoscopic Images

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1125] opened 2020-10-06 06:18 UTC
Neos is already able to display 360 stereoscopic images, and from what I could tell, capturing them doesn't seem too hard either. Could support for his kind of image capture be added? It's been mentioned a few times before but I don't believe it ever made it into the GH. Low priority.

**Comment by Frooxius** [comment] 2020-10-06 06:22
Capturing 360 stereoscopic images is actually quite hard and it's the reason why it's not supported right now. There are many different ways to do it with varying quality of results. Best combination of efficiency and correctness is through shader support, which displaces vertices appropriately. However this requires all shaders to be modified accordingly and some additions/modifications to the interfacing to the rendering system.

**Comment by H3BO3** [comment] 2020-10-06 06:25
I see, that's interesting to know. I know VRChat is able to capture those kinds of photos, I'm kind of confused on how they're able to do it with all the custom shaders there. Are there other somewhat less-accurate ways of capturing images like that?

**Comment by Frooxius** [comment] 2020-10-06 06:29
I think they're using the built-in Unity Stereo 360 capture: https://blogs.unity3d.com/2018/01/26/stereo-360-image-and-video-capture We'd likely build on top of this functionality too, although it's a bit more complicated with Neos.

For most shaders it should be relatively quick or fully automated addition. Not sure how well it translates to all shaders. This technique doesn't provide fully accurate results (that's technically not even possible with stereo 360, you'd need something like a lightfield), but works well enough for most things.

**Comment by H3BO3** [comment] 2020-10-06 06:33
That's pretty interesting. I definitely understand how working with a unity function like that could be more complicated in Neos, hopefully it could be worked on someday! Thanks for entertaining the thought for a bit, it's good to know why it's not already in the engine.

**Comment by shiftyscales** [comment] 2020-10-06 07:02
This is also a duplicate of #505. It would be a nice eventual addition though, yes.

**Closed by shiftyscales** 2020-10-06 07:02 UTC
Labels: Duplicate, Enhancement, Low Priority
