### ISSUE TITLE
Validation state in component attacher for generics always displays invalid

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1565] opened 2021-01-04 05:34 UTC
## Describe the bug
When using the component attacher, some components such as DynamicReferenceVariable<T> and ReferenceCopy<T> will show 'Invalid', even though they are properly formatted. The 'Invalid' button can still be pressed, however, and the component will spawn as expected.

## To Reproduce

1.  Open Inspector on Empty Object
2. Press 'Attach Component'
3. Navigate to any generic type which accepts references (DynamicReferenceVariable<T>, ReferenceCopy<T>, etc)
4. Type in a valid custom type name
5. Observe that the validation text remains 'Invalid'

## Expected behavior
The validation text should accurately reflect whether the type is a valid reference type for the target component.

## Screenshots / Video
![Component Attacher with Generics](http://files.aerizeon.net/sharex/2021/Neos_01-04jcTgbdM1Sl.png)
![Component Attacher with Generics](http://files.aerizeon.net/sharex/2021/Neos_01-04rhs7t659bG.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2021.1.3.1256
 - Neos Platform: Windows
 - Regression: Yes (From 2020.12.24.35)

## Additional context
Related to hotfix for #1562

## Reporters:
Epsilion
Hayden

**Edit:**

It seems this is the same underlying issue as #1572

In this case, it is a NRE caused by `IsValidGenericType`, which occurs when `GetType` passes it a null `Type` object
It seems patching `IsValidGenericType` with a null check on the incoming `Type` resolves this issue.

**Comment by ProbablePrime** [comment] 2021-01-06 01:18
Im also experiencing this but I have a workaround, this might help in diagnosis too:
- Open the type selector as above
- Type something in, like above
- Hit Back
- Then select the component again
- Then re-type the type again
- THIS time the "Create Custom Generic Type" button will show

So essentially the second time through that window it'll work as intended but not on the first.

Seems to be this way for each time I want to add something :(

**Comment by TehTurk** [comment] 2021-01-06 01:24
I think it's visual, if you click on the field where it says "Invalid Type" but you "Know" it works, it'll generate it.

**Comment by Frooxius** [comment] 2021-01-11 10:59
Fixed in 2021.1.11.642, thanks!

**Closed by Frooxius** 2021-01-11 10:59 UTC
Labels: Bug
