### ISSUE TITLE
Neos Camera should spawn photos relative to it/the user's scale

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#418] opened 2020-03-05 20:38 UTC
1. make yourself big
1. spawn a neos camera
1. take a photo
1. Observe that the photo spawns very small, probably at the size it would if your avatar was at world scale.

I only noticed this last night so Im not sure if im able to reproduce but its quite straight forward to test.

**Comment by shiftyscales** [comment] 2020-03-05 21:59
In testing this out, I've observed that this behavior occurs with the standalone camera object. Photos taken by other means such as the stream camera, or the finger photo do spawn out at a size relative to the player's current scale.

The photo's scale appears to be tied to the `PhotoSpawnSize` property of the `InteractiveCamera` component.

As another potential quality of life suggestion- it could be beneficial for photos taken to have a larger default spawning size. In a lot of cases, shortly after taking a photo, a user will immediately resize it so it is a more appropriate scale for viewing, and sharing among others in a session.

**Comment by ProbablePrime** [comment] 2020-03-05 23:04
@shiftyscales I wouldn't class this as UI/UX. A bug though yes.

**Comment by shiftyscales** [comment] 2020-03-06 01:43
I'm not sure that it is a bug in this case though, @ProbablePrime. As observed, there is a property in the camera component to control the size the photo spawns out in, and that is working as intended from the testing I've done. So at that point, I'd say it could be a UX thing as it's changing a behavior to one that is more convenient for users.

The inconsistency with the behavior the stream camera and finger photo camera suggest it might be though. I'll add the tweak tag as either way a minor change in behavior is desired.

**Comment by ProbablePrime** [comment] 2020-03-06 01:46
I see what you're saying, i guess im disagreeing with the intended behaviour here without understanding what the intended behaviour should be.

My belief is that I and other users would most likely expect this to function how i describe in the issue title.

At the end of the day its just a label though.

**Comment by Frooxius** [comment] 2020-03-09 11:43
Should be fixed in 2020.3.9.689! Thanks!

**Closed by Frooxius** 2020-03-09 11:43 UTC
Labels: UI/UX, tweak
