### ISSUE TITLE
Folders cloned, and placed in a different spot in inventory, break(All contents deleted/not there) after deleting original folder

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#276] opened 2019-07-28 08:08 UTC
Didn't know if this was intended but showed someone else the bug and told me it was a bug as well and should let you know on the github. I do know a UI update is inbound to some degree, so if this is known, sorry didn't see anything pop up for this after searching.

**Comment by Frooxius** [comment] 2019-07-28 08:15
By cloned do you mean using the orange envelope button? There's no way to actually clone folders right now, the envelope only makes a hyperlink.

That's an expected behavior, because deleting the original will make the link invalid.

**Comment by TehTurk** [comment] 2019-07-28 08:22
Ah yes! Apologies then. Was attempting to organize my inventory and did not realize it was hyperlinking and not creating an object for the folder. Sorry for the commit!

**Comment by Frooxius** [comment] 2019-07-31 05:01
No problem! Once the UI is being reworked it'll be a little clearer as there will be labels and descriptions for all these buttons. I'm closing this issue for now

**Closed by Frooxius** 2019-07-31 05:01 UTC
