### ISSUE TITLE
Heavy lag when duplicating custom arcs.

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1685] opened 2021-01-28 16:59 UTC
## Describe the bug
When injecting custom arcs into the ArcLayout (Duplicate Logix Node) the game stutters heavily. It only started recently.

## Relevant issues
#1628 Possibly?

## To Reproduce
Spawn my tool: 
neosrec:///U-3x1t-5tyl3/R-de5be452-3271-428d-bb9d-bc0034b0c1ea -> Tools -> My Multitool -> Spawn it out and open the Context Menu after being in a session for a prolonged period of time. (As far as I can recognize it usually 10-15 minutes.

## Expected behavior
The moment I made the tool (november 20 through early january 21) it worked without any lag spikes. I've asked mars, anything and a few others and all can attest (see below: regression) it started happening after the "shader" update (v 2021.1.17.1026 being the latest working version.)

## Screenshots / Video
https://www.youtube.com/watch?v=DAsxaF-Q2eA

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes and no. Requires a prolonged period in a session.
 - Neos Version: 2021.1.27.369 (or earlier. Not sure. Wasn't around too much this last week and a half.)
 - Neos Platform: Any
 - Link to reproduction World/Item: See above.
 - Regression: Yes **(2021.1.17.1026)** (According to: marsmaantje#3356, AnythingItDoesn'tReallyMatter#7078 aswell as myself.)

## Additional context
While looking through the log I did not find aynthing *at all* that says anything about the arcs that are being duplicated. (Log states sometimes nothing for minutes.) Happy to provide them anyways though.
https://discord.com/channels/402159838827905024/655375765596274756/803264026540113940
https://discord.com/channels/402159838827905024/439422161657135106/804344985579159563
Possibly related: Duplicating alot of materials at once causes major hitch aswell. I assume this can apply to this "UIX" component aswell?

## Reporters:
かず#0617, Hayden#3180, 3x1t_5tyl3#0001, chemicalcrux#1298

See the japanese channel. @Frooxius already saw the convo 2? days ago with rabbutz.

**Comment by chemicalcrux** [comment] 2021-01-28 17:01
I observed a similar problem in a friend's world: they were duplicating four text renderers for each player, and even with just two people, this was causing a noticeable hitch. The culprit was material components: moving them out so that they were not duplicated made it work cleanly.

However, I have no way to check if the duplication of materials has become more expensive, since it would've happened several versions ago.

**Comment by chemicalcrux** [comment] 2021-01-28 17:16
I did a little testing. Duplicating the Outline text object (the one you can spawn via the devtool) causes a hitch.

* A Basic textwith the Outline material assigned to it is fine
* A Basic text with the Outline material component cloned onto it, but not used, is fine
* A Basic text with the Outline material component cloned onto it *and assigned to be used* causes the hitch
* An Outline text whose material has been configured to exactly match the Basic text's material still causes the hitch. They even reference the same shader!

I do not observe this hitching with any other material (or, at least, I haven't run into it yet).

**Comment by Frooxius** [comment] 2021-01-29 08:38
Thanks for the detailed report! I'm pretty sure that this is due to the shader providers being duplicated heavily and accumulating heavily. I've made changes in 2021.1.29.504 that cleans up the old shader providers and also prevents them from being saved with the object now.

Can you check if the issue still persists please?

**Comment by 3x1t-5tyl3** [comment] 2021-01-29 09:19
Unfortunately this still seems to happen.
I also noticed it becomes laggier and laggier the more I open the arcmenu. In the video I opened and closed it for about 2 minutes before having very significant hitches. Though I could also feel it with the first opening becoming progressively more significant the more I open it.

Quick video: 
https://user-images.githubusercontent.com/61988002/106256010-07d57200-621b-11eb-8622-4b6f6818bd28.mp4

**Comment by chemicalcrux** [comment] 2021-01-29 15:25
Important correction: I didn't notice that Basic text does not spawn with its own material. If I clone its default material onto it and assign it to its material field, it produces the same hitching behavior as Outline text.

A Box with the Basic text's material cloned onto it and assigned does not cause hitching. Basic text with a default PBS_Metallic material cloned onto it and assigned does cause hitching.

So, rather than being something that mysteriously only happens to the Outline text, it seems to be related to the text renderer component.

**Comment by 3x1t-5tyl3** [comment] 2021-01-29 19:13
I found a temporary solution by making the tool use one material refference instead. Though for text that uses different materials each in the future this might still needed to be looked into. 
See: https://discord.com/channels/402159838827905024/655375765596274756/804677732327227392

**Comment by Frooxius** [comment] 2021-02-03 10:30
Thank you for the detailed info, I was able to narrow down the cause thanks to it with a profiler, I'm pretty sure it should be all good in 2021.2.3.616 now! Optimized a few things on top of it as a result too!

**Closed by Frooxius** 2021-02-03 10:30 UTC
Labels: Bug
