### ISSUE TITLE
Putting a Video Texture Output into a Volume Meter without setting its url will return a random user's Volume level instead of 0

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1051] opened 2020-09-20 04:35 UTC
repro steps: be in a world with multiple people in it
setup a slot with a video Texture Output and a Volume Meter on it

connect the video Texture Output to the Volume Meter

the volume Meter will output some user's volume level.

https://cdn.discordapp.com/attachments/533413898057941023/757097614373290004/2020-09-19_20.08.37.webp

**Comment by Enverex** [comment] 2020-09-20 04:43
It's not a random user's volume AFAIK, it's repeating a part of the audio buffer or something else as weird. I and others have run into this issue a lot when creating visual effects based on volume meters (I've seen the issue myself when working in a world alone, in silence - after the video that was playing ends, thus it couldn't be another user's audio).

**Comment by shiftyscales** [comment] 2020-09-20 07:36
I believe this is a duplicate of #523. From that issue as well- the issue only reportedly happens with Unity Native video playback, and not LibVLC.

The issue might also potentially be remedied by the addition of the LibVLCSharp library once it is implemented.

**Closed by shiftyscales** 2020-09-20 07:36 UTC
Labels: Duplicate
