### ISSUE TITLE
Community Toon Shader +What Features

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#428] opened 2020-03-14 19:04 UTC
Figured having a general overview of what types of features Froox should keep or cull for a toon Shader, custom made or community made. Please list any features that should be included. 

Some included are 
- Specular Support
- Cubemap /Environment Support
- Shadow Ramping

**Comment by MrMegaTronic** [comment] 2020-03-14 19:19
I feel on top of all features, the big benchmark is how GOOD of a toon-shader it is.  Shader features tend to change from person to person because of tastes.  But things like "Does it react to the environment and light sources properly?  e.g. does it go completely dark in a black environment?" or "under a light source does it light up evenly or does it become a supernova?"  make for a good starting ponit.

Beyond that, MY feature desires are the three Turk listed above along with 

- Rim support with adjustments for intensity and falloff
- Backface control for one and two sided faces.
- HDR input support for things like over-driven specular effects and emission effects.

**Comment by sinni800** [comment] 2020-03-15 04:18
- lighting ramps (that would need some sort of editor i'm thinking)
- feathering
- multiple shade textures
- subsurface scattering
- rim lighting
- specular reflections
- show backfaces (same color as front, current shader is weird.)
- blinking emission/scrolling emission
- glow in the dark is kinda cool (become more emissive with lighting), because you could have a different emissive color, so it's actually a different color in the dark!
- ambient occlusion maps

**Comment by Frooxius** [comment] 2020-03-15 15:26
I think some of those features are better left to be driven by LogiX, like the scrolling, blinking and so on, to keep the shader itself simpler.

Can you also provide some examples of what exactly do you expect under certain functions, as well as their priorities? The more it needs to have the longer it's going to take to implement, but having a prioritized list could allow it to grow over time.

Another question is, is there an existing shader that satisfies those needs? E.g. the Xiexes shader? It's looking like an interesting candidate, but I don't know if it's better to integrate that one or build a custom one from scratch.

**Comment by sinni800** [comment] 2020-03-15 16:01
These are mostly features I took from Poiyomi that was suggested as an example. 

- lighting ramps (shadow ramps) -> these are used to ramp the shadow behaviour. basically with a ramp you can have multiple shadow levels (like a 3-step shading) which can result in some interesting effects. If you look at the game Killer7 for example, they used a shadow ramp with I think 4 hard steps. Can be very useful and I would give it a medium priority. Would need a GUI to configure the ramp.
- feathering -> I am actually not 100% sure if this is not just a different way to go about shadow ramps. This is a feature of the [Unity-Chan shader ](https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/blob/master/Manual/UTS2_Manual_en.md). 
- Multiple Shade Textures -> another Unity-Chan feature. The textures are basically layered on top of each other... I don't 
- Subsurface Scattering -> makes for a cool effect when light goes through a thin part of the model (like pointing a flashlight at your hand, making it glow). Nice to have, it's just another "on-top" effect.
- Rim Lighting -> In a lack of global illumination, this is a good trick to make characters light up around their borders, for example when the light comes from the front. Makes things a bit more believable I think. 
- Speculars -> I would say pretty high. Speculars on toon make the toon "stick out" more, it's for example a style chosen for Zelda Breath Of The Wild. Gives it more depth. 
- Show backfaces -> Very high priority in my opinion. This saves a LOT of tris for cloth, for example. Also less annoying as you don't have to two-ply cloth and be careful it doesn't intersect.
- Blinking/scrolling -> I only added this because Poiyomi (again) had it, and if you were to include Poiyomi almost verbatin and only by removing functionality, it would have not been trouble. Would still agree with Logix, but I would also make the argument that at least blinking would be a one-liner even in shader language
- Glow in the dark -> Eye candy, kinda cool. I feel mostly this would give people who have avatars like Nexulean has a boost. for cool looking glowy lights. I can for example imagine that this would make an effect possible, where the emissive (glow-in-the-dark) color is oversaturated (>1.0 values) and thus has the glaring effect while the regular albedo has not. It would make the brightness difference between the glowy parts and the other parts more apparent especially through lighting changes. When the environment is bright, something would not necessarily be glare-y for you, but it would when it's dark.
- AO maps -> This would also again give the toon shader the possibility to pass more as "very 3D toon", as the occlusion shadows give depth. 

Well, the shaders I know are Xiexie, NoiNoi, Poiyomi, Reflex, Unity-Chan mostly. Poiyomi has most of the things I listed except for the AO maps. Another issue I find though is that it seems like all of those shaders look very different from each other even with base settings. This makes me think there's somewhat of an aesthetics argument here... Also, as many of them are made for VRChat specifically, they have some hacks iirc regarding lighting, as many world makers don't set up lighting probes. Some of them even have fake shadows so you dont have to rely on the world having lights (except for fixed ambient amounts with no direction). It kinda looks weird though when only one avatar has random shadows on them and everyone else is in the shadeless ambient light without shadows. The fake shadow system is one thing I would honestly probably not want to see coming over to Neos. 

As for the aesthetics differences argument... Honestly, you should probably try these out in the editor, you will probably see what I mean. 

I honestly can't say if it's better to build one from scratch at this point or take something existing. For one, a lot (all?) of these shaders seem to live in pre-HDR and many have no notion of PBR.

**Comment by Hacksawfred3232** [comment] 2020-03-15 18:44
Most of these functions, I wouldn't see the value in adding in the backend personally. A good hack in textures and with more LogiX nodes exposing underlying functionaility would do the trick. Although, I personally would like to argue about the blinking and scrolling functionailty. While doing blinking emission is fairly easy to do depending on the route you take, scrolling emission is a no go and wouldn't even work within the current LogiX engine as it involves real time texture manuplation. Adding the functions in the backend is the only way of having them work in the game flawlessly

**Comment by sinni800** [comment] 2020-03-15 18:47
> scrolling emission is a no go and wouldn't even work within the current LogiX engine as it involves real time texture manuplation. 

Wouldn't just manipulating the texture position do this? Not sure to be honest if it's the right effect

**Comment by Hacksawfred3232** [comment] 2020-03-15 18:53
> 
> 
> > scrolling emission is a no go and wouldn't even work within the current LogiX engine as it involves real time texture manuplation.
> 
> Wouldn't just manipulating the texture position do this? Not sure to be honest if it's the right effect

This would only work with avatars where the texture would allow it AND/OR you want a simple scrolling effect. For more complicated avatars, you wouldn't be able to pull this effect off easily.

**Comment by sinni800** [comment] 2020-03-15 23:47
I've checked out how the Poiyomi shader does it, and here are the relevant lines: 

https://github.com/poiyomi/PoiyomiToonShader/blob/master/_PoiyomiShaders/Shaders/Includes/PoiEmission.cginc#L86

Is it just me or does it actually just offset the texture position?

**Comment by Hacksawfred3232** [comment] 2020-03-16 00:01
More like it scrolls a line across the emission map. So techincally speaking, it overlays the emission map across the texture, and then scrolls a while line across the emission map. You can't do that within the current LogiX engine. I will be damed if you can find a work around for it though.

**Comment by Frooxius** [comment] 2020-03-16 14:13
It doesn't really have much to do with LogiX, because it's not shader specific, it just lets you control all the properties in arbitrary ways (including material/shader properties), in that regard it's already fully featured.

The only question is if achieving given effect is possible by manipulating the shader's input parameters or not. If it's not, then it's fundamentally impossible to achieve with LogiX (meaning there's no change or addition to LogiX that would enable that), since the shader is simply not capable of that behavior.

So it's a question of which functionality needs to be added to the shader and which properties should be exposed to achieve desired effect.

As general rule, I try to bake as few specific behaviors into shaders as possible and design them in more generic ways, so the individual specific effects can be achieved by controlling the shader properties externally. That keeps the shader simpler and opens a lot more options and controls for manipulation.

**Comment by Hacksawfred3232** [comment] 2020-03-16 14:30
Well, there is one way we can do it... maybe. Maybe having a "emission scanning map" (A texture that controls what part of the emission map is visible, in the same style of the emission map itself) that can be offset from a certain point can certainly pull off the scrolling trick, as well as opening up some other options. How one would implement it would be interesting though.

**Comment by Frooxius** [comment] 2020-03-16 18:28
I'm looking into the Xiexe toon shader. It has a few issues that I'm not too happy with (it's not using variants at all, for pieces that it should, which are instead done as branches in the shader code which can be very suboptimal in some cases), but the code is a lot more cleaner so I could adjust that. 

I think this shader is a lot better candidate for adding it in for now. It doesn't have all the features that are requested it seems (like the glitter), but could potentially work for the time being.

One thing I'm still worried is how it will translate in the future and if we can maintain it. One possibility is to not expose some of the more fringe functions and in the future do a replacement for our custom one and automatically translate existing materials to our new one.

That would likely lead to some visual changes though, depending on the differences. 

Question is, is it a big problem if that happens at some point in the future or if preserving the exact look is really important (which means this shader would have to be maintained and potentially upgraded long term). If so it might be better to just wait for our own.

**Comment by sinni800** [comment] 2020-03-16 18:35
Another feature I found that would be pretty helpful is a spherical texture maps. This can help with cheaply making highlights for example. MMD models very frequently use that feature. Also they have shadow grading like I mentioned above and different kinds of toon maps, there is even a number of toon maps that is included by default in MMD itself. With MMDs being pretty popular, I think looking into it might be worthy at some point.

Honestly, if it's somewhat easy to include, how about including whatever toon shader you choose as a "temp" toon shader ("will be gone at some point") in addition to the current stable one. It would be like a "dev" shader that is allowed to change, also based on user feedback, and allowed to break.

This way we can experiment with it and grow this with feedback. Then we can either slowly take functionality over to the stable shader or decide some other way.

**Comment by Frooxius** [comment] 2020-03-16 18:40
Problem is that even if something is marked as temporary, people end up using it as if it wasn't and then they get confused or angry when it's removed or changed later on. It's hard to ensure that is communicated properly and people understand the implications. 

Maintaining long term compatibility is one of the important things in Neos, so I want to reduce breakage as much as possible, at the cost of getting some things sooner.

**Comment by sinni800** [comment] 2020-03-16 18:42
I guess all you can do it put it in red front on top of the material settings. Maybe make them invisible to choose unless you use the Neos Launcher and turn on a big red checkbox? I'm sure there's some way one can communicate "here be DRAGONS" sufficiently

**Comment by TehTurk** [comment] 2020-03-16 18:43
I don't know, for certain experimental features like local write I can understand having warning, but Materials should be forward thinking until they can be touched again.

**Comment by sinni800** [comment] 2020-03-16 18:45
I honestly think we need some way of "seeing" how a material and shader implementation harmonizes with everything else in Neos. 

For example I was never really too favorable about the way Poiyomi shaders look, I don't know, it was always kind of off to me.

**Comment by Frooxius** [comment] 2020-03-16 18:45
You'd be surprised how many people can ignore big red warnings. But it's not so easy, they can find it through lots of different ways, that would be impossible to cover. E.g. they make a duplicate of the material. Or want to use it during import. 

If we skip some of the functionality though, then the conversion later on shouldn't be that drastic to cause too many issues though, so we might just bite the bullet and add this one for now if it provides big enough benefit to counter the negatives.

**Comment by sinni800** [comment] 2020-03-16 18:48
Honestly, if most of the features are disabled (except very sane to have ones, like backfaces) we can at least use it to tell what I've been saying in the previous comment... Different shaders just look differently aesthetically, and I think we'd want something with as little opinion on it as possible. 

The current toon shader does this very well, I have to say. It's very neutral.

**Comment by Hacksawfred3232** [comment] 2020-03-16 18:49
Well, concerning I managaged to gloss over the fact that "_" means internal values (and caused my game to crash doing that), I would not be surprised that people would have ignored the big red warnings.

I'm up for adding features to the current toon shader if it comes to that.

**Comment by TehTurk** [comment] 2020-03-16 18:51
Of the stated suggestions
- Specular/Metallic/AO Support
- Cubemap/Environment
- Shadow/Light Ramping
- Stronger Rim Control
- Backfaces 
Shoot out to me as generalized/upgraded features.

**Comment by Hacksawfred3232** [comment] 2020-03-16 18:52
I would like to also opt in for better emission control by using an "overlay" texture on top of the already existing emission map. Although, I would need Elektrospy's input on that concerning if the existing options does the job already.

**Comment by sinni800** [comment] 2020-03-16 18:53
I agree with this set of features, Turk.

**Comment by TehTurk** [comment] 2020-03-16 19:02
If we can shrink down more tho I'd think that be better, from how they are describe and from what I've worked with getting things to work in Neos, I oft not find some features are just the same thing but named differently and applying different maps as an option, or scaling the map. Because Backface and Rim could be the same vein, shadows/light/enviro/cubemap sounds like they share similar properties too, but just be like extra maps that can be applied, like main, detail, secondary. Because if it's toon, it Should be toon, not a toon shader trying to be a metallic or specular shader that requires some tweaking.

**Comment by Hacksawfred3232** [comment] 2020-03-16 19:23
From the Neos discord:
![image](https://user-images.githubusercontent.com/16674456/76792747-9a178780-67bb-11ea-9835-853e0a0212ce.png)
Consider the scrolling emissive part solved then.

**Comment by orange3134** [comment] 2020-03-18 02:58
In addition to the previous suggestions, I want the following features:
-Outline width map (Use a map texture to specify the thickness of the outline for a specific area. For example, avoid outlines in the eye sockets and lips.)
-Screen space outline width (The outline width is constant from any distance.)
-Blend Main Texture color to outline color
-Shadow color
-Shadow threshold (Shift shadow boundaries)
-Shadow Blur (Blur the border of the shadow)
-MatCap
-ClippingMask (Example: https://twitter.com/KrullFuerst/status/1225689391038812160)
-SceneLights Hi-Cut Filter (Function to suppress overexposure)

**Comment by shiftyscales** [comment] 2020-03-20 14:51
From the Discord since I have seen it discussed and suggested numerous times, I figure I'd report and document some requested features for the shader now that it's been added, some of which @Frooxius has already mentioned that he plans to add.

- Cutout, alpha, and transparency blend modes for textures
- Shadow edge blending

**Comment by anima1020** [comment] 2020-03-23 07:37
Here are suggestions for the features I'd like to have added to the Xiexe Toon Shader.


1. Add Detail Normal Map, Detail Mask, and Specular Map

2. Add Main Texture, Normal Map, Detail Normal Map, Detail Mask, Specular Map, Emission Map, Occlusion Map, Thickness Map Tiling (scale) x,y and Offset x,y.


I think the usability of the shader is expanded if what I mentioned above is added. Please consider these suggestions.

**Comment by wel97459** [comment] 2020-03-23 18:35
> Here are suggestions for the features I'd like to have added to the Xiexe Toon Shader.
> 
> 1. Add Detail Normal Map, Detail Mask, and Specular Map
> 2. Add Main Texture, Normal Map, Detail Normal Map, Detail Mask, Specular Map, Emission Map, Occlusion Map, Thickness Map Tiling (scale) x,y and Offset x,y.
> 
> I think the usability of the shader is expanded if what I mentioned above is added. Please consider these suggestions.

I also noticed too that the Tiling Scale and Offsets were missing.

**Comment by shiftyscales** [comment] 2020-08-26 03:06
Since XiexeToon has long since been implemented, and has now fully replaced FlatLitToon, I think this issue can be closed. If anyone has any desired additions, a separate issue could be made per request to keep things manageable.

**Closed by shiftyscales** 2020-08-26 03:06 UTC
Labels: Enhancement, Materials
