### ISSUE TITLE
Autojoin LAN sessions opens all accessible sessions

### ISSUE THREAD

**Issue by maxer456** [Frooxius/NeosPublic#1016] opened 2020-09-12 22:35 UTC
Checking the "Autojoin LAN sessions" checkbox in the Neos launcher makes Neos join all accessible sessions, not just those available on the LAN.

The option also seems to make the dash inaccessible. Is that expected?

**Comment by shiftyscales** [comment] 2020-09-12 22:43
Hiding the UI is apparently intended behavior. I believe the autojoin LAN option is primarily intended to be used for more controlled experiences/environments.

Autojoining ALL sessions doesn't sound like correct behavior at all, though.

How many sessions are being joined/what sessions are joined? Do you have a log for that session, @maxer456?

`However just using "Autojoin LAN sessions" should work well enough, since it hides the UI.`
https://discordapp.com/channels/402159838827905024/439421735474036738/568437846856433684

**Comment by maxer456** [comment] 2020-09-12 22:59
Here's the log file for the session: [2020.9.9.214 - 2020-09-12 23_38_41.log](https://github.com/Frooxius/NeosPublic/files/5213350/2020.9.9.214.-.2020-09-12.23_38_41.log)

I could see Neos connecting to both empty headless sessions and normal user sessions. It was freezing a lot and ended up running out of memory and crashing, so I don't know how many I ended up joining.

**Comment by mralext20** [comment] 2020-09-12 23:00
[ALEXDESKTOP - 2020.9.9.214 - 2020-09-12 14_20_51.log](https://github.com/Frooxius/NeosPublic/files/5213352/ALEXDESKTOP.-.2020.9.9.214.-.2020-09-12.14_20_51.log)

_maybe_ related to named sessions?

**Comment by shiftyscales** [comment] 2020-09-12 23:03
I see. That is pretty strange. Thank you for following up, and providing those logs.

**Comment by Frooxius** [comment] 2020-09-14 08:39
Fixed in 2020.9.14.511 thanks!

**Closed by Frooxius** 2020-09-14 08:39 UTC
Labels: Bug
