### ISSUE TITLE
Request for a lit text material

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1141] opened 2020-10-12 16:16 UTC
It would be nice to have a material that is affected by world lighting for text. This would be especially useful for creating UI that is lit by the world and doesn't need to be full-bright.

**Comment by shiftyscales** [comment] 2020-10-12 18:26
This is a duplicate of #784. At the time it was initially requested, @Frooxius had needed to think up how best to handle it technically.

**Closed by shiftyscales** 2020-10-12 18:26 UTC
Labels: Duplicate
