### ISSUE TITLE
Kiosk mode: disable user's radial hand menus

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#342] opened 2019-12-08 00:31 UTC
It would be desirable of the user did not have the radial hand menus available in `-Kiosk` mode.

This is an attempt to remove this as a possible point of confusion for users who have no need of this functionality, which I assume is one of the main purposes of kiosk mode.

If this isn't intended for this mode, is there another way to accomplish this?

**Comment by TehTurk** [comment] 2019-12-08 19:17
Think you could delete the menus on the avatars that are used to showcase.

**Comment by ProbablePrime** [comment] 2019-12-08 19:22
You can currently disable them in the user spawner its a checkbox

**Comment by Frooxius** [comment] 2019-12-08 20:25
This is odd, Kiosk mode should already do this. I have just tested it and it behaves correctly on my end. Can you tell me more about your setup?

**Comment by sirkitree** [comment] 2019-12-08 20:38
Steps I took to reproduce:
- add -Kios to steamvr settings:
![Launch Options - Neos VR 2019-12-08 12 33 40](https://user-images.githubusercontent.com/28543/70395765-001f9200-19b7-11ea-9d2e-bbf7b12c2c3f.jpg)
- put on headset (Index)
- hit controller power (Index) which boots up steamvr
- start neos from within steamvr

Note that my local home loads, then my cloud home, and there is no main dashboard (good). Upon hitting the B button, see radial hand menus open up (not good).
![20191208123722_1](https://user-images.githubusercontent.com/28543/70395819-9653b800-19b7-11ea-88d0-a7c7a7453e48.jpg)

**Comment by Frooxius** [comment] 2019-12-08 20:50
Ah I see what the problem is. You're currently host of those worlds. Currently the Kiosk mode is setup so you join another session hosted by someone else (e.g. headless or another station). The menus won't be there. If you're the host they will show up.

I can change it so they don't show at all in the next build.

**Comment by sirkitree** [comment] 2019-12-08 21:00
Thanks! I believe that the use case here is the machine will be the host so it would be very useful to not allow the radial menus. Much appreciated! :)

**Comment by Frooxius** [comment] 2019-12-08 21:06
Ok I'll make the change and push a new build in a bit.

**Comment by Frooxius** [comment] 2019-12-08 23:02
Okay fixed in 0.8.18.42547 and pushed out!

**Closed by Frooxius** 2019-12-08 23:02 UTC
Labels: Kiosk mode, bug
