### ISSUE TITLE
Logix Delete Path will get stuck

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#541] opened 2020-05-14 08:11 UTC
Repro steps are to grab and drag, but then let go while holding, when you requip it'll persist or at least keep trying to draw the tip.

**Comment by shiftyscales** [comment] 2020-05-14 18:10
This is a duplicate of #374 and a known issue in general. Closing this issue.

**Closed by shiftyscales** 2020-05-14 18:10 UTC
Labels: bug, duplicate
