### ISSUE TITLE
Desktop View in Dashboard with Portrait Orientation Keeps 16:9 Aspect Ratio in Landscape

### ISSUE THREAD

**Issue by FreyarH** [Frooxius/NeosPublic#1607] opened 2021-01-17 01:35 UTC
## Describe the bug
When using the Desktop View in the Dashboard and using the secondary option to select a secondary monitor set in portrait mode, the view will stretch horizontally instead of preserving a 9:16 aspect ratio (or rather respecting the portrait resolution set), causing anything on it to be unreadable.

## To Reproduce
1. Connect or enable a secondary monitor.
2. Go to Windows 10 Settings > Display > Scale and Layout > Display orientation.
3. Set Display orientation to "Portrait (flipped)" and save.
4. Start SteamVR and Neos.
5. Open the dashboard and the desktop view.
6. Press Secondary and select the Portrait (flipped) monitor.

## Expected behavior
The display for the desktop view will be oriented in portrait mode similar to how Steam's Overlay does.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Neos Version: 2021.1.13.764
 - Neos Platform: Windows
 - Regression: No

## Additional context
Steam Overlay manages to respect the portrait configuration and permit the ability to read it.

## Reporters:
@Freyar#1337

**Comment by Frooxius** [comment] 2021-01-17 06:30
Hmm this is a bit strange, since there should already be handling for the portrait screens. I've only tested with "Portrait" though, so it might be the flipped version that doesn't work. Would you be able to check if "Portrait" (the not flipped one) works correctly in Neos?

**Comment by FreyarH** [comment] 2021-01-17 07:22
When setting the secondary monitor to "Portrait" mode, the direction of the text will invert but the same display issue will be present.

As shown on Neos Dashboard. (Apologies for strange angles, I don't know how to take screenshots appropriately of the dash.)
![Neos_2021-01-17_00-13-34](https://user-images.githubusercontent.com/77557994/104833882-43566080-5859-11eb-94a7-2cb24c2fc0e8.jpg)

As written in Notepad, with the secondary monitor in Portrait (standard) mode.
![notepad_2021-01-17_00-14-10](https://user-images.githubusercontent.com/77557994/104833888-4a7d6e80-5859-11eb-9c4f-a1f2d88cd35b.png)

A theory came to mind. I have four monitors total.

1. Dell S2716DG on Display Port to RTX 3080 (Landscape)
2. ACER S241HL on HDMI to RTX 3080 (Landscape)
3. ACER S241HL on HDMI to Onboard (Intel UHD Graphics 630) (Landscape)
4. Dell S2409W on DVI to Onboard (Intel UHD Graphics 630) (Portrait Flipped)

Is it possible this is due to the fourth monitor being handled by the onboard chipset instead?

**Comment by Frooxius** [comment] 2021-01-17 16:59
Yeah the integrated card is probably the cause since Neos needs to use alternate capture method for it. Should be fixed in 2021.1.17.998 now, please reopen if the issue still persists as I don't have a way of testing this. Thanks for report!

**Closed by Frooxius** 2021-01-17 16:59 UTC
Labels: Bug

**Comment by FreyarH** [comment] 2021-01-18 03:41
Tested in version 2021.1.17.998 on 17JAN2021 with success.
