### ISSUE TITLE
FPS facet breaks

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#791] opened 2020-07-20 07:23 UTC
I'm not certain on a replication case yet, but there is something that is causing the FPS facet to break.

For myself it is stuck on the last FPS value displayed, e.g. in my case, 70. Rukio has also previously had this issue. Rebooting Neos doesn't fix it. When I extracted the facet to my inventory, and spawned it into the world- the user field wasn't filled. Once I placed my user ID in, it began to work again. Hopefully that helps, I'll update with more information as I learn more.

**Comment by TehTurk** [comment] 2020-07-20 07:27
I'm aware of what causes it. There's a User Field/Target and it can be null sometimes, is it just the default Facet? No Tweaks?

**Comment by Frooxius** [comment] 2020-07-20 07:39
Hmm that's odd. What were the other fields for the User reference? It's odd that it has broken the reference, we'd need to find a way to reproduce how it happens.

**Comment by shiftyscales** [comment] 2020-07-20 08:35
It happens when the local database is deleted/the machine ID is modified, @Frooxius.

Steps to replicate:
- Clear the local database
- Log in to Neos
- Your dashboard will sync, but the facet will be using the old machine ID, and thus won't properly update your user reference

**Comment by shiftyscales** [comment] 2020-07-20 08:37
If I restore the old local database, the facet begins working again because the machine ID it's expecting is restored too.

**Comment by Frooxius** [comment] 2020-07-20 18:32
I see. That's a bit odd, since it should've saved the actual cloud UserID as well. I'll make some changes though so it always restores the user when it's in the Userspace, that should take care of it. Thanks!

**Comment by Frooxius** [comment] 2020-07-24 07:41
Fixed in 2020.7.24.446 thanks!

**Closed by Frooxius** 2020-07-24 07:41 UTC
Labels: bug
