### ISSUE TITLE
TipTouchSource components should respect directionality

### ISSUE THREAD

**Issue by Coffee-Maker** [Frooxius/NeosPublic#1185] opened 2020-10-21 13:31 UTC
When using physical touch to interface with certain UI elements it is far too easy to accidentally double-press an element because the tip doesn't respect directionality. A video will best demonstrate the problem: https://i.gyazo.com/333bc2c340dc7b60a2d0d1d3009568f8.mp4

This would greatly improve the experience of interfacing with leap motion.

**Comment by shiftyscales** [comment] 2020-10-21 18:28
This is a duplicate of #799.

**Closed by shiftyscales** 2020-10-21 18:28 UTC
Labels: Duplicate, Enhancement
