### ISSUE TITLE
Integration of bHaptics TactSuit

### ISSUE THREAD

**Issue by MR-Alex42** [Frooxius/NeosPublic#584] opened 2020-05-24 13:25 UTC
https://www.bhaptics.com/tactsuit/ is a full body haptics solution gaining momentum  (support for VRChat, Half-Life Alyx, etc.). It runs wirelessly with on all the platforms that NeosVR supports and works nicely together with vive trackers for full body tracking. They are offering a C# SDK and Unity integration.

**Comment by Frooxius** [comment] 2020-05-24 14:10
This could be added, but we'd need to get a dev-kit for integration to be efficient and well done. Do you know if they offer any dev-kits to developers?

**Comment by MR-Alex42** [comment] 2020-05-24 15:27
Sure. I'll ask them if they can provide dev -kits to developers.

**Comment by Enverex** [comment] 2020-05-26 14:21
This is a duplicate of a much older request - https://github.com/Frooxius/NeosPublic/issues/404

**Comment by shiftyscales** [comment] 2020-05-26 18:52
So it is, thanks, @Enverex. Closing this issue. Please let us know what you find on #404, @MR-Alex42.

**Closed by shiftyscales** 2020-05-26 18:52 UTC
Labels: Hardware
