### ISSUE TITLE
Finger Pose Source Driver breaking on user join

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1251] opened 2020-11-01 19:29 UTC
Encountered and reported by RezilloRyker# 3830, a driver from a finger pose node is being broken when a user joins a session.
I recreated the issue using this simplified setup of driving a ValueField<floatQ> with the Finger Pose node as follows:
![2020-11-01 11 18 15](https://user-images.githubusercontent.com/54213390/97812203-9cd4c900-1c34-11eb-984c-f9a8783ad04b.png)

The same issue occurs while explicity specifying a user with User From ID as well.

If I had to guess, I believe the finger data stream is momentarily lost which breaks the connection/driver, and it doesn't automatically reattach itself.

**Comment by Frooxius** [comment] 2020-11-01 19:53
Do you have a log for it breaking?

**Comment by shiftyscales** [comment] 2020-11-01 19:58
Yes, doesn't seem to have anything of note, but here you go, @Frooxius: 
[SHIFTYWINDOWS - 2020.10.30.1068 - 2020-11-01 11_54_33.log](https://github.com/Frooxius/NeosPublic/files/5471645/SHIFTYWINDOWS.-.2020.10.30.1068.-.2020-11-01.11_54_33.log)

**Comment by Frooxius** [comment] 2020-11-01 20:02
Thanks!  Hmm, could you check the values of User Finger Pose Source and see if it's null or not? What exactly happens with the outputs of Finger Pose? Does it revert to default values or does it get stuck on last ones?

**Comment by shiftyscales** [comment] 2020-11-01 20:15
The display node for the output of finger pose turns red, but continues to display the proper values, the user finger pose source doesn't appear to go null- at least not in the display node pulled from it. Because the driver is removed, the value field that was being driven displays the last value it had before the drive was broken.

Interestingly- the break happens right around the moment the joining user's streams get initialized (once they finish loading in, and begin being tracked instead of just being head/hands at their origin.)

**Comment by mralext20** [comment] 2020-11-01 20:17
this feels like the same root cause as #1242, where the value streams go null when someone is joining a session.

**Comment by Frooxius** [comment] 2020-11-01 20:22
Hmm, if it's going red, that means there's an exception. Are you sure you sent me the right log? Or can you get me the log from the other person you tested with, it might've happened on their end.

**Comment by Frooxius** [comment] 2020-11-01 20:23
It's unlikely to be the same cause as #1242 since this node doesn't store/manage the stream references at all, it fetches the data dynamically.

**Comment by shiftyscales** [comment] 2020-11-01 20:29
Okay, a couple more logs. This one is from myself (host, and the user that the nodes were under/referencing) and Vigilabo.

I had Vigilabo restart Neos, join my session, and leave.

My log: 
[SHIFTYWINDOWS - 2020.10.30.1068 - 2020-11-01 12_24_05.log](https://github.com/Frooxius/NeosPublic/files/5471690/SHIFTYWINDOWS.-.2020.10.30.1068.-.2020-11-01.12_24_05.log)

Vigil's: 
[DESKTOP-7Q9M270_-_2020.10.30.1068_-_2020-11-01_15_24_10.log](https://github.com/Frooxius/NeosPublic/files/5471691/DESKTOP-7Q9M270_-_2020.10.30.1068_-_2020-11-01_15_24_10.log)

**Comment by Frooxius** [comment] 2020-11-01 20:30
Ah I see the exception in Vigil's log, will fix in next build, thanks!

**Comment by Frooxius** [comment] 2020-11-01 22:09
Fixed in 2020.11.1.1319 thanks!

**Closed by Frooxius** 2020-11-01 22:09 UTC
Labels: Bug
