### ISSUE TITLE
AssetFrameSlots are very aggressive at grabbing assets

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#695] opened 2020-06-17 20:21 UTC
Hamish and I were in a world with 0utsider's picture frame and periodically it would grab images from across the map.

It appears to be similar in its inaccuracy to the recent ToolShelf issues.

It is more repeatable if you first put an item into the frame and then remove it.

Here's a workflow to test:
1. Spawn 0utsider's picture frame or my Material Frame 4.1
1. Spawn any picture, and place it in the frame
1. Grab the picture out of the frame and move it geographically away from the frame
1. Drop the picture and see it get agressively sucked back into the frame

In all cases the colliders for these frames are a small rectangle around the frame about 1.5 times wider than the frame so the picture is most certainly leaving the collider's range.

**Comment by H3BO3** [comment] 2020-06-17 20:26
I've noticed this too. There seems to be no "range" property on the component which could help, but otherwise it just grabs it back from seemingly infinite distances once an asset is initially dropped into it. You have to replace it with another one to get it to stop grabbing the old one.

**Comment by shiftyscales** [comment] 2020-06-17 20:27
Perhaps I never properly logged it, or it was never fixed, or it's a regression. But this behavior has been noted before.

https://discordapp.com/channels/402159838827905024/439422161657135106/701627321760612402

https://cdn.discordapp.com/attachments/439422161657135106/701628596795473920/2020-04-20_03-00-07.mp4

`@Frooxius#4483 @ChrisWarner103#8178 @ToMo#1337- I've isolated the issue. When an asset has a text renderer on it, e.g. the audio clip, that is what causes the problem to occur where it is unable to escape being brought back into the asset frame.`

This could be an extension of that, and/or a related issue.

**Comment by ProbablePrime** [comment] 2020-06-17 20:27
I think its meant to be collider based, the component has a collider property on it which is usually linked to a nearby box collider.

**Comment by H3BO3** [comment] 2020-06-17 20:29
Interesting that text on the asset would cause it. I was working with audio players too when I noticed this behavior

**Comment by Frooxius** [comment] 2020-11-08 10:12
Should be fixed in 2020.11.8.605!

**Closed by Frooxius** 2020-11-08 10:12 UTC
Labels: Bug, Components
