### ISSUE TITLE
Projection 360 rendering AO improperly

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#931] opened 2020-08-25 05:52 UTC
See attached screenshot.
Material: projection360
![20200825074801_1](https://user-images.githubusercontent.com/61988002/91128083-ce1aa100-e6a7-11ea-8265-dc60edad79e5.jpg)
I'd have to test more unlit materials when I have more time. But I know there's probably a few more that also have this AO rendering issue.

**Comment by Frooxius** [comment] 2020-08-25 06:05
What does your Projection360 look like? Did you modify any of the default settings? It shouldn't do this by default, but changing the Render Queue and other related parameters can do this. 

Materials aren't responsible for rendering AO, that's a post-processing effect that happens after materials have rendered. Generally with unlit materials like this you have to make sure they are in the right Render Queue so they render after the AO.

**Comment by 3x1t-5tyl3** [comment] 2020-08-25 06:20
Using the default material orbs, no customisation. "Neos essentials -> skyboxes".
The default material orbs. See screenshot below.
![20200825081837_1](https://user-images.githubusercontent.com/61988002/91130252-a4fc0f80-e6ab-11ea-8bb3-b2cb41975e0f.jpg)

**Comment by Frooxius** [comment] 2020-08-25 06:37
The Neos Essentials -> Skyboxes aren't default, they're configured to be rendered as skybox and not meant to used for in-world objects.

Skyboxes can't use -1 because that will use the wrong render queue for a skybox and cause various rendering issues.

If you want to use the same 360 material for skybox and in-world objects, create a duplicate of it, you can't use the same instance, since they need to be configured slightly differently. I'm closing this issue as this is expected behavior.

**Closed by Frooxius** 2020-08-25 06:37 UTC
