### ISSUE TITLE
Dash updates cut off voice messages

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#1592] opened 2021-01-13 21:44 UTC
## Is your tweak request related to a problem? Please describe.
Dash updates prevent listening to longer voice messages as the chat also gets regenerated while playback is in progress

## Describe what would you like tweaked
Preferably only the parts of the dash that update should be regenerated to avoid the cutting off of voice messages

## Describe alternatives you've considered
None that are possible on the user-side, unless you want to spawn an audio source in your userspace and manually copy the URL into it to avoid the problem.

## Additional context
Considering the concise nature of this problem, no additional context is needed I think.

**Comment by H3BO3** [comment] 2021-01-13 21:45
Duplicate of #1336, closing

**Closed by H3BO3** 2021-01-13 21:45 UTC
Labels: Tweak

**Comment by RileyGuy** [comment] 2021-01-13 21:58
Woops, forgot I already made one of these.
