### ISSUE TITLE
AxisMultiViewportPanner request

### ISSUE THREAD

**Issue by candypheonixIO** [Frooxius/NeosPublic#1366] opened 2020-11-19 20:20 UTC
Can the AxisMultiViewportPanner component work like the "ScreenManager" Component found in the Dash? The reason I'm asking for this is because of some cases were animated screens would be nice, but if there are more than 2 screens, I'd rather not have to watch two screens scroll past as I navigate to the main viewport of the UIX panel.

**Comment by Toxic-Cookie** [comment] 2020-11-19 20:48
Duplicate of this issue: https://github.com/Frooxius/NeosPublic/issues/1210

**Closed** 2020-11-19 20:52 UTC
Labels: Duplicate
