### ISSUE TITLE
Bug With Mirrors on PiMax HMD

### ISSUE THREAD

**Issue by KacperLa** [Frooxius/NeosPublic#548] opened 2020-05-14 22:12 UTC
Hello, 
It seems that there is an issue regarding Mirrors and the Pimax headset. Any mirror I look at renders a completely different perspective for each eye.  It looks like my avatar is standing in two different places. I attached images taken through both lenses while I was standing in the same exact spot. Let me know if I can provide any more info. 

Thank you in advance!!

Left Eye:
![image](https://user-images.githubusercontent.com/42217156/81990725-ba25c480-960d-11ea-8431-b70ea9aafd86.png)

Right Eye:
![image](https://user-images.githubusercontent.com/42217156/81990759-c90c7700-960d-11ea-8f77-8a38591c550a.png)

**Comment by shiftyscales** [comment] 2020-05-14 22:18
Hey. Thanks for the report, but this is a duplicate of #309. Would you mind trying out adjusting the Pimax FOV and other settings, and report back on issue #309 letting me know if that changes anything?

**Closed by shiftyscales** 2020-05-14 22:18 UTC
Labels: duplicate
