### ISSUE TITLE
ColliderUserTracker doesn't deregister users on respawn

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1110] opened 2020-10-03 18:51 UTC
Steps to replicate:
- Have a user inside the volume of a collider using a ColliderUserTracker
- Respawn the user
- The user remains listed under _usersInside and the IsAnyUserInside and IsLocalUserInside (if applicable) remain checked
- If the user re-enters the collider volume, a second entry is added for them under the _usersInside
- If they exit the volume normally their entries will clear normally as expected

Issue observed by Turk.

**Comment by TehTurk** [comment] 2020-10-03 20:43
Ah thanks for making this Shifty, I wanted to make this but actually wanted to add something as having it behave this way has it's uses as my MMC map currently.uses the behavior. So if possible, could it also be added as an option to keep it in some form?

**Comment by shiftyscales** [comment] 2020-10-03 20:47
You can easily replicate that behavior in the absence of this bug by having a boolean that is set on the activation, but never reset for the local user (or globally). In doing so, you could easily create a trigger that activates just one time (either per-user or per instance).

It feels like it could be outside of the scope of this component to permanently track if a user has ever been inside of the collider's volume, but I understand the utility/what you wish to do with it.

**Comment by TehTurk** [comment] 2020-10-03 23:46
Yes, you could replicate the behavior but that isn't what I was talking about. It's less so it's expected use case is still indeed used, but due to the bug another usecase came from it, so I just want to enable the more options for users. Sometimes the phrase it's not a bug it's a feature :0 occurs sometimes. 

Hmm but it does this already quite so, I was wondering if we could just determine if the events for it to have more control of the trackers behavior, get the same effect to now, but also fix the bug as well.

**Comment by Frooxius** [comment] 2020-10-04 20:17
Fixed in 2020.10.4.1198, thanks for report! A bigger fix later on will require refactoring of the event system for physics engine, which should fix all occurrences of this in all places.

As a rule, I don't preserve behavior of bugs as an option, that would make things very messy and hard to maintain long term. The responsibility of this component is to track if user is inside the volume or not so it should stay that way.

If you want to track if user just entered the volume, I recommend using the LogiX OnCollisionStart event and just write a bool, that's most efficient way to do it. If you'd like a component to be considered for that I'd suggest a separate issue, but this isn't something that would fit component too well.

**Closed by Frooxius** 2020-10-04 20:17 UTC
Labels: Bug

**Comment by TehTurk** [comment] 2020-10-04 21:27
All good thanks for the explanation Froox. Just please understand this currently now breaks my MMC world :)

**Comment by Frooxius** [comment] 2020-10-04 21:28
What exactly does it break? Is it a serious breakage or is it only when user gets respawned by accident? I could temporarily revert the fix for the duration of judging.

**Comment by TehTurk** [comment] 2020-10-04 21:31
Nah it was used in mind of as one time check sort of gate. I mentioned this prior earlier in the issue. I wouldn't mind as I know Prime also uses this as well for his map too. I don't know if anyone else uses it currently.

**Comment by Frooxius** [comment] 2020-10-04 21:32
Ok I'll keep it then. If it's a minor breakage that doesn't hurt the entry it should be good then! For gated checks like that I'd just recommend the OnCollisionStart node, it's optimal for such use-case.

**Comment by TehTurk** [comment] 2020-10-04 21:37
No sorry if I was unclear, if you don't have it, you won't be able to start the game proper o.o, it's because I needed the behavior of players leaving and exiting a zone, but, on respawn the zone is ignored and things are switched.

**Comment by Frooxius** [comment] 2020-10-04 21:38
Oh so do you need the bugfix to be reverted in order to make your entry playable?

**Comment by TehTurk** [comment] 2020-10-04 21:39
Yes regretfully.

**Comment by Frooxius** [comment] 2020-10-04 21:43
Ok reverted in 2020.10.4.1300, sorry I misunderstood what you meant. Once MMC judging is over the bug will get fixed again.

**Comment by TehTurk** [comment] 2020-10-04 21:46
It's okay it happens. No Problem.
