### ISSUE TITLE
Add Debug Visuals for Colliders

### ISSUE THREAD

**Issue by RueShejn** [Frooxius/NeosPublic#901] opened 2020-08-15 13:57 UTC
this is a request to add debug visuals for colliders
setting up capsule colliders and others is very difficult without being able to visualize them

**Comment by shiftyscales** [comment] 2020-08-15 16:29
This is a duplicate of #454. I would also like to see this implemented in some form as it's not often easy to select, and modify just the colliders.

For some collider types you can visualize and edit them (green lines/dots) by pressing one of the boxes on the gizmo, @RueShejn.

**Closed by shiftyscales** 2020-08-15 16:29 UTC
Labels: duplicate
