### ISSUE TITLE
Option to join or create session without switching to it

### ISSUE THREAD

**Issue by uyjulian** [Frooxius/NeosPublic#1254] opened 2020-11-02 19:01 UTC
There should be an option so that when you click on a world orb or on the world menu, you can join or create the session without switching worlds.  

This would allow you to do stuff (e.g. finish a conversation) in a loaded session while the joined session is loading.

**Comment by shiftyscales** [comment] 2020-11-02 19:08
This is a planned UI option, but it's not a priority right now. This issue can be considered as a duplicate of #65. But thanks for the suggestion, @uyjulian!

**Closed by shiftyscales** 2020-11-02 19:08 UTC
Labels: Duplicate
