### ISSUE TITLE
midi input component 

### ISSUE THREAD

**Issue by mintytriforce** [Frooxius/NeosPublic#1684] opened 2021-01-28 01:19 UTC
## Relevant issues
instruments cant be controlled by a midi keyboard

## Describe the solution you'd like
a midi input component that takes midi and makes it usable to control different things such as sounds that are played and other audio related things

**Comment by ProbablePrime** [comment] 2021-01-28 01:20
This is unfortunately a duplicate of: https://github.com/Frooxius/NeosPublic/issues/97

**Closed by ProbablePrime** 2021-01-28 01:20 UTC
Labels: Duplicate, Enhancement
