### ISSUE TITLE
AND nodes breaking attached nodes and themselves when removing inputs

### ISSUE THREAD

**Issue by Ardescar** [Frooxius/NeosPublic#654] opened 2020-06-06 15:09 UTC
Found while retracing the "world not open" issue and the bugs i had in this world. So i showed Shifty the bug with the deletion of the logix nodes on my blueprint.

Video of how it looks on my side: https://strzl.de/video/dele.mp4
While Shifty got a freezing Neos - on my side just some logix nodes are dissapearing
And it is replicable exactly like shown in that video.

The blue print was saved from a bigger project and is a part of that.
I saved it in my inventory while the strands to the INTtoStr still have been connected to the bigger project.

It seems that the order of removal of those nodes on the left side is important. 

Logfile with Shifty online in my world and he is freezing when i tried to delete the [String";"] after i deleted the multiline string addition:
[ARDI - 2020.6.5.201 - 2020-06-06 16_31_46.log](https://github.com/Frooxius/NeosPublic/files/4740491/ARDI.-.2020.6.5.201.-.2020-06-06.16_31_46.log)

How it did look after i tried to remove it:
![logixshifrty](https://user-images.githubusercontent.com/63201013/83947595-45166b00-a818-11ea-81c3-d999f796a899.png)

**Comment by Hayden-da-Serg** [comment] 2020-06-06 15:25
This may be an issue with the Blueprint itself, I'll have to take a look at it and see what's going on, as that is most definitely not intended behaviour.

**Comment by shiftyscales** [comment] 2020-06-06 15:25
As was mentioned, for remote users like myself, when the nodes were deleted, Neos locked up and many exceptions are thrown. We collected two samples in the form of these logs:

[SHIFTY-PC - 2020.6.5.201 - 2020-06-06 07_00_02.log](https://github.com/Frooxius/NeosPublic/files/4740513/SHIFTY-PC.-.2020.6.5.201.-.2020-06-06.07_00_02.log)
[SHIFTY-PC - 2020.6.5.201 - 2020-06-06 07_12_56.log](https://github.com/Frooxius/NeosPublic/files/4740514/SHIFTY-PC.-.2020.6.5.201.-.2020-06-06.07_12_56.log)

A world will be provided that has the blueprint. To replicate the issues, there are two nodes that need to be deleted in sequence as demonstrated in the video clip. For Neos to lock up, you will need to be a client/remote user, for Neos to show the nodes deleting, you will need to be host.

**Comment by Hayden-da-Serg** [comment] 2020-06-13 18:06
Okay, talked with @Coffee-Maker and tested, this is indeed not an issue to do with the Blueprint and seems to be a general exception, as we were able to recreate it without touching the Blueprint, I was the host for both sessions and Coffee was deleting the nodes, logs from both are provided below.

[HAYDEN-LAPTOP - 2020.6.12.785 - 2020-06-13 11_57_19.log](https://github.com/Frooxius/NeosPublic/files/4775134/HAYDEN-LAPTOP.-.2020.6.12.785.-.2020-06-13.11_57_19.log)
[HAYDEN-LAPTOP - 2020.6.12.785 - 2020-06-13 04_13_53.log](https://github.com/Frooxius/NeosPublic/files/4775135/HAYDEN-LAPTOP.-.2020.6.12.785.-.2020-06-13.04_13_53.log)

Both gave the same results as the issue above, Neos completely locking up for the host user.

**Comment by shiftyscales** [comment] 2020-06-13 18:11
Hmm? That's odd, @Hayden-da-Serg. In our test cases, Neos would only fully lock up for remote users in the session. The host user would instead just show the nodes getting deleted as shown in the above video.

**Comment by Hayden-da-Serg** [comment] 2020-06-13 18:23
Okay, it's relatively easy to recreate, get a + node with more than 2 inputs, then plug an input to any slots on the node then make an output, then delete the + node and this may cause the input node to error, deleting the input node causes Neos to lock up for every user except the one deleting the node.

**Comment by shiftyscales** [comment] 2020-06-13 18:31
Oh okay. So it is consistent with our findings. Nice. Thanks for finding that simplified replication case! I replicated it with those steps too.

That should hopefully make it easier for either @Coffee-Maker or @Frooxius to look into a potential fix. 👍

**Comment by shiftyscales** [comment] 2020-06-13 18:32
[SHIFTY-PC - 2020.6.12.785 - 2020-06-13 11_30_23.log](https://github.com/Frooxius/NeosPublic/files/4775202/SHIFTY-PC.-.2020.6.12.785.-.2020-06-13.11_30_23.log)

**Comment by Earthmark** [comment] 2020-06-17 19:40
Art007i, Guillefix, and I ran into this as well although we didn't need to delete nodes to get it to work:
Connecting the same input node to both inputs of a plus node and then expanding the amount of arguments in the plus node and then reducing the arguments back down to 2 creates a red input node,
at this point breaking the connection between the plus node and the input will crash everyone else than the person who is breaking the connection
breaking the connection can be done in multiple ways:
- deleting either node
- cutting one of the wires
- changing where the node is wired up to

It does seem like the behavior isn't always reliable, and sometimes doesn't hit everyone in the server. 
Here's my log from one such crash that was based on this set of actions.
[DESKTOP-5HFQ42U - 2020.6.16.1192 - 2020-06-17 00_20_15.log](https://github.com/Frooxius/NeosPublic/files/4794736/DESKTOP-5HFQ42U.-.2020.6.16.1192.-.2020-06-17.00_20_15.log)

**Comment by Ardescar** [comment] 2020-06-17 19:53
ahh yes i have seen with art007i once in the past that nodes turning red by reducing the amount of inputs. But at that point i did not investigate it further because nothing happened back then.
Interesting that this turns out to be kind of the same problem. Thanks for adding this replication to the issue.

**Comment by shiftyscales** [comment] 2020-06-20 22:23
This issue has also been observed, replicated, and reported by Beaned, PurpleJuice, and H3BO3.

**Comment by shiftyscales** [comment] 2020-06-20 22:27
https://cdn.discordapp.com/attachments/439422161657135106/724015791225176205/2020-06-20_23-36-56.mp4 Footage provided by Beaned.

**Comment by Frooxius** [comment] 2020-06-21 00:31
Thanks for the simple replication case, this should make it easy to fix. From the log it looks like it's some problem with walking the node inputs and outputs, probably some order of operation things, I'll investigate a bit more.

Is it specifically just the AND nodes? Or does it happen with others as well, such as OR, other operators and so on?

**Comment by shiftyscales** [comment] 2020-06-21 00:37
I just replicated it on OR, +, -, multiply, and other operators. It seems to be most of, if not all operators that you can add/remove an input from in testing so far, @Frooxius.

**Comment by Frooxius** [comment] 2020-06-21 15:33
Thanks for the info, I've got a fix coming in the next build! Fortunately it was a simple fix with the data you provided. Turns out it was also cause of this issue: https://github.com/Frooxius/NeosPublic/issues/710

**Comment by Frooxius** [comment] 2020-07-05 13:31
Forgot to close this, it's already fixed a bunch of builds back.

**Closed by Frooxius** 2020-07-05 13:31 UTC
Labels: LogiX, bug, high priority
