### ISSUE TITLE
Grabber Simulator

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#777] opened 2020-07-15 16:48 UTC
A native system for creating and controlling arbitrary grab spheres that behave like the ones on the hands, along with the necessary logix nodes.

**Comment by shiftyscales** [comment] 2020-07-15 19:28
This is a duplicate of #424.

**Closed by shiftyscales** 2020-07-15 19:28 UTC
Labels: Components, LogiX, duplicate, enhancement

**Comment by H3BO3** [comment] 2020-07-15 19:29
dangit
