### ISSUE TITLE
importing a model creates weird tangents on a model

### ISSUE THREAD

**Issue by AegisTheWolf** [Frooxius/NeosPublic#782] opened 2020-07-16 19:14 UTC
Note: This happened to one model so far from importing it directly from blender (if I run into more with similar issues i can test the same things I did with this mesh in case if the model is the issue), I can provide the model and only certain parts of the model had abnormalities.
When inspecting the meshes with the mesh tool I tried recalculating the normals with no change, then trying the mikktspace tangent option, then the simple tangent option and it fixes the tangents of the model.

**Comment by AegisTheWolf** [comment] 2020-07-16 19:22
![2020-07-16 14 20 36](https://user-images.githubusercontent.com/65252793/87713305-9b5bbf80-c76f-11ea-96ef-0dfe29b75aed.jpg)
![2020-07-16 14 19 59](https://user-images.githubusercontent.com/65252793/87713310-9c8cec80-c76f-11ea-91b7-531601483a76.jpg)
After the mesh was calculated in simple the mikkt works as intended.

**Comment by DanteTucker** [comment] 2020-07-16 22:10
I was about to file an issue related to this as I have had multiple reports of newly imported models appearing as all black until the tangents are recalculated as "simple".

I have a sample model which appears as black if you need it, i just can't post it here for privacy

**Comment by Frooxius** [comment] 2020-07-16 22:26
Can you send me the models that are having problems please? It sounds like something is going wrong with the Mikktspace. Does it happen to all models? Or only part of the model?

**Comment by DanteTucker** [comment] 2020-07-16 22:51
The example model I sent you is having issues with only part of the model. However I have encountered several people since the update where it affected the whole model.

**Comment by AegisTheWolf** [comment] 2020-07-17 18:24
Ok after some investigation here is a idea of what could be causing it: Pre-applied normal maps to the model from an external program creates this issue with the tangents and here is the screenshots of blender to neos. I hope these help ya froox.
![unknown](https://user-images.githubusercontent.com/65252793/87818762-c1956400-c830-11ea-8928-660f6aaa147d.png)
![2020-07-17 13 19 39](https://user-images.githubusercontent.com/65252793/87818780-c6f2ae80-c830-11ea-99bd-3745083f65e7.jpg)
![unknown (1)](https://user-images.githubusercontent.com/65252793/87818788-c9ed9f00-c830-11ea-9e7c-553ec962217d.png)
![2020-07-17 13 20 39](https://user-images.githubusercontent.com/65252793/87818797-cd812600-c830-11ea-92ab-5e24e0051df7.jpg)

**Comment by Frooxius** [comment] 2020-07-17 20:03
I've looked into this. It's caused by incorrect face indexing when there are multiple submeshes. Fix coming in the next build!

**Comment by Frooxius** [comment] 2020-07-17 22:06
Fixed in 2020.7.17.1288, thanks!

**Closed by Frooxius** 2020-07-17 22:06 UTC
Labels: bug
