### ISSUE TITLE
Logix relay goes to point 0,0,0 when made behind a cast

### ISSUE THREAD

**Issue by Beaned2000** [Frooxius/NeosPublic#1045] opened 2020-09-18 16:15 UTC
So the issue is that whenever you make a relay node by grabbing a wire with the logix tool on a logix wire that came from a cast, the relay node would reset its position to the center point of the world

 **Replication steps:**
- let a variable cast
- grab the wire behind the cast with the logix tool

**Comment by H3BO3** [comment] 2020-09-18 16:22
This is a duplicate of #918 .

**Closed by H3BO3** 2020-09-18 16:22 UTC

**Comment by H3BO3** [comment] 2020-12-17 15:41
If you wanna give the original issue a thumbs up, that would help with getting it addressed
