### ISSUE TITLE
Keyboard sometimes spawns inside your head

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#417] opened 2020-03-05 20:35 UTC
Depending on the state of your avatar's face the keyboard can sometimes spawn inside your head making it difficult to interact with.

From experimentation it seems like the keyboard functionality does some form of raycast before spawning to decide on the position.

Examples where this occurs:
* If there's a gizmo on or near your head
* Wearing hats of certain kinds
* Being in confined spaces
* having UI open and really close to your face such as the inventory screen. 

This is a minor frustration really but still something to note.

**Comment by shiftyscales** [comment] 2020-03-06 01:51
What would be your proposed/preferred labels to have? It's not explicitly a coding issue/bug as things seem to be working as intended- just how they're intended happens to be inconvenient for users, hence it's a UX improvement to not have the keyboard spawn in a user's head.

**Comment by ProbablePrime** [comment] 2020-03-06 01:56
I dont particularly mind, I just don't feel this meets the traditional meaning of UI/UX and more closely aligns to the bug definition. Ultimately i'd like Froox to take a look and let us know what he thinks of this particular issue, instead of discussing the merits of various labels.

**Comment by Frooxius** [comment] 2020-03-08 08:48
I've known about this issue, but it's kinda tricky one. It's designed to prevent keyboard and other things from spawning behind things, but sometimes the raycast hits something too close.

I could add some minimum distance, but that could lead to things spawning behind stuff in some cases again, so I feel like it might be better to address the issue differently (e.g. using something that always renders through and changing the positioning mechanics of a bunch of things in general).

I'll probably see about revisiting this after some of the UI/UX overhaul, unless you feel this happens often enough that it'd warrant a mitigation right now?

**Comment by Frooxius** [comment] 2020-03-09 11:44
Should be fixed in 2020.3.9.689 for now. It's not ideal solution, but I'll see what we can do going forward if there are still issues. Closing this one for now. Thanks!

**Closed by Frooxius** 2020-03-09 11:44 UTC
Labels: UI/UX
