### ISSUE TITLE
CharacterParenter Component Still Functions Even if Disabled

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#723] opened 2020-06-29 16:41 UTC
Disabling the CharacterParenter component doesn't actually seem to disable it and it'll continue working as though it was still enabled.

**Comment by Zyzyl** [comment] 2020-06-29 21:19
This is also the case with the CharacterTeleporter and CharacterForceField components in the same category.

**Comment by TehTurk** [comment] 2020-07-01 11:59
These behaviors I think should be flagged by a color of some sort if possible :o, there are some stuff in the game that won't turn off, or the enabled bool is completely useless.

**Comment by Zyzyl** [comment] 2020-07-01 12:56
@TehTurk do you mean that there are components where disabling them is known by the community not to affect anything AND that Froox has confirmed this is intended behavior? If so, I agree some indicator should be provided and the useless bool should be removed. However, to my mind it would be better from a user perspective if disabling any component predictably disabled any related functionality, effectively making it as if the component didn't exist unless re-enabled. I don't know if there are technical reasons that this would be difficult / undesirable though.

**Comment by Frooxius** [comment] 2020-07-02 02:42
Fixed in 2020.7.2.150!

**Closed by Frooxius** 2020-07-02 02:42 UTC
Labels: Components, bug
