### ISSUE TITLE
[Tweak] Optimize how meshes are imported

### ISSUE THREAD

**Issue by Toxic-Cookie** [Frooxius/NeosPublic#1361] opened 2020-11-19 02:43 UTC
Most of the time, a mesh collider is unnecessary and awful for performance. However, an imported mesh will come in with this menace to society. Please replace it with a box collider that is the size of the bounds of the object.

**Comment by Frooxius** [comment] 2020-11-19 07:12
I'm sorry, bit this won't be implemented. This will work well only for a small subset of all meshes, there are many where box collider would be far too large and cause a lot of confusion to users and unexpected behavior (yes I tried). Creating optimized colliders is something that needs to be done by the user.

**Closed by Frooxius** 2020-11-19 07:12 UTC

**Comment by Hayden-da-Serg** [comment] 2020-11-20 07:13
As an alternative, maybe have an option to set up primitive colliders very similarly to how skinned meshes have approximate colliders on import? I do come across a few cases in which the default mesh collider on import is very detrimental to a workflow due to the frame impact that comes along with lasers interacting with dense mesh colliders.

**Comment by Frooxius** [comment] 2020-11-20 08:47
How would you do that? It works for skinned meshes because it has bones, so colliders can be generated that follow the bone structure. For static meshes don't have this data at all, so this approach is not applicable. 

The closest thing would be running a convex hull decomposition, but that requires manual configuration to work well and can take significant amount of time to compute, so it's not really good choice either.
