### ISSUE TITLE
Allow the ability to disable Desktop View

### ISSUE THREAD

**Issue by Zandario** [Frooxius/NeosPublic#1521] opened 2020-12-23 21:52 UTC
As the title says, I'd love to have a option to disable Desktop View, I personally use a Quest 2 and it becomes redundant, especially since I can do more using Virtual Desktop anyways, but the real gripe I have is that ever since this was added/in-development, I can no longer run NeosVR without SteamVR which breaks so many things for me.

These things include but not limited to: 
- Random FOV-Increases causing "Fish Eye" especially when you open/close the oculus menu.
- Sudden studdering where the view snaps back and forth for no understandable reason (seemed to be fixed by opening and closing the SteamVR Menu.
- **Massive** performance drops.
- Touch Capacitance Sensor for the Thumb Rest looses complete function.

**Comment by Frooxius** [comment] 2020-12-23 22:31
Disabling the Desktop View won't help with those issues, it's not the cause. I don't see a reason to disable Desktop View otherwise, simply don't use it if you don't want it.

Since your issue seems to be more about running through SteamVR, I'm going to close this issue as duplicate, as we have one for that already here: https://github.com/Frooxius/NeosPublic/issues/1520

**Closed by Frooxius** 2020-12-23 22:31 UTC

**Comment by shiftyscales** [comment] 2020-12-23 23:53
@Zandario - regarding performance drops- if you are using an Nvidia card, Steam has recently been putting out this warning/notification:

> Note: Some users with NVIDIA GPUs are experiencing dropped frames with SteamVR 1.15. If you encounter this issue on a 10xx or 20xx card, consider [rolling back your GPU drivers](https://www.nvidia.com/Download/Find.aspx) to 446.14. This resolved the issue for many people.

https://store.steampowered.com/newshub/app/250820/view/2931245981685839445
