### ISSUE TITLE
Delete-Laser of LogixTooltip always visible after interrupting deletion

### ISSUE THREAD

**Issue by InnocentThief** [Frooxius/NeosPublic#553] opened 2020-05-17 20:22 UTC
The delete laser of the logix tooltip will not be deleted after interrupting the process with a hoovering over a belt menu button.

1. Equipe Logix Tooltip
2. Start deleting (trigger) and hold trigger
3. Open belt menu
4. Hoover over a button on the belt (with Logix Tooltip) 
5. The deletion gets interrupted
6. Close the belt
7. Click the trigger
8. Delete Laser is always visible
![2020-05-17 22 06 15](https://user-images.githubusercontent.com/65510170/82159174-bd7ab380-988c-11ea-914a-bf7f9622a9a8.jpg)

**Comment by TehTurk** [comment] 2020-05-17 21:39
This is a duplicate of #374

**Closed by TehTurk** 2020-05-17 21:39 UTC
